In [ ]:
'''
1. **¿Tenemos actores en la tabla de actores que comparten el nombre completo y, en caso afirmativo, muestran esos nombres compartidos?**

Para responder a esa pregunta, primero necesitamos saber si tenemos actores en la tabla de actores que comparten sus nombres completos. Entonces comenzar contando la cantidad de actores que comparten sus nombres completos.
'''

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT CONCAT(first_name,' ', last_name) Nombre_completo, COUNT('Nombre_completo')
FROM actor
GROUP BY 1
HAVING COUNT('Nombre_completo') >1;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Susan Davis', 2)]

In [ ]:
'''
2. **Muestra los nombres de los clientes que comparten la misma dirección (por ejemplo, esposo y esposa).**

Para responder a esta pregunta, debemos buscar más de un cliente que tenga el mismo address_id pero diferentes customer_ids. Eso significa que haremos JOIN a la tabla de clientes para sí mismo (*autounión*).
'''

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
	c1.first_name,
	c1.last_name,
	c2.first_name,
	c2.last_name
FROM
	customer as c1
	join
	customer as c2
ON c1.customer_id <> c2.customer_id AND
	c1.address_id = c2.address_id
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  address_id,
  COUNT(address_id)
FROM
	customer
GROUP BY address_id
ORDER BY COUNT(address_id) DESC
LIMIT 3;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(6, 1), (7, 1), (5, 1)]

In [ ]:
'''3. **Muestra el monto total pagado por todos los clientes en la tabla de pagos.**

Utilizar aquí la función agregada **SUM()** en la columna de monto de la tabla de pagos.'''

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  SUM(amount) as Suma
FROM
	payment
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

#import pandas as pd
#df = pd.DataFrame(result)
#print (df[0])

[(Decimal('61312.04'),)]

In [ ]:
print(result[0][0])

61312.04

In [ ]:
#4. **Muestre el monto total pagado por cada cliente en la tabla de pagos.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  customer.first_name, customer.last_name, SUM(payment.amount)
FROM
	payment
RIGHT JOIN
 customer
ON
  customer.customer_id = payment.customer_id
GROUP BY
  customer.customer_id;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[('Vivian', 'Ruiz', Decimal('80.80')),
 ('Wanda', 'Patterson', Decimal('137.72')),
 ('Dan', 'Paine', Decimal('106.79')),
 ('Priscilla', 'Lowe', Decimal('130.72')),
 ('Guy', 'Brownlee', Decimal('151.69')),
 ('Alice', 'Stewart', Decimal('123.70')),
 ('Chris', 'Brothers', Decimal('77.80')),
 ('Kay', 'Caldwell', Decimal('65.87')),
 ('Christina', 'Ramirez', Decimal('75.83')),
 ('Yolanda', 'Weaver', Decimal('102.75')),
 ('Juan', 'Fraley', Decimal('63.79')),
 ('Mathew', 'Bolin', Decimal('84.80')),
 ('Dwayne', 'Olvera', Decimal('95.80')),
 ('Billie', 'Horton', Decimal('71.79')),
 ('Kyle', 'Spurlock', Decimal('109.71')),
 ('Nathan', 'Runyon', Decimal('121.69')),
 ('June', 'Carroll', Decimal('151.68')),
 ('Morris', 'Mccarter', Decimal('135.68')),
 ('Christopher', 'Greco', Decimal('113.75')),
 ('Misty', 'Lambert', Decimal('102.78')),
 ('Raul', 'Fortier', Decimal('86.82')),
 ('Penny', 'Neal', Decimal('56.84')),
 ('Laura', 'Rodriguez', Decimal('94.81')),
 ('Bertha', 'Ferguson', Decimal('89.77')),
 ('Travis', 'Estep', Decimal('91.78')),
 ('Armando', 'Gruber', Decimal('72.82')),
 ('Pedro', 'Chestnut', Decimal('97.78')),
 ('Erik', 'Guillen', Decimal('115.72')),
 ('Jenny', 'Castro', Decimal('79.80')),
 ('Audrey', 'Ray', Decimal('111.73')),
 ('Shawn', 'Heaton', Decimal('142.69')),
 ('Cassandra', 'Walters', Decimal('96.79')),
 ('Deanna', 'Byrd', Decimal('90.78')),
 ('Brett', 'Cornwell', Decimal('130.70')),
 ('Carolyn', 'Perez', Decimal('111.71')),
 ('Loretta', 'Carpenter', Decimal('87.79')),
 ('Geraldine', 'Perkins', Decimal('94.76')),
 ('Edith', 'Mcdonald', Decimal('69.83')),
 ('Marsha', 'Douglas', Decimal('142.66')),
 ('Ethel', 'Webb', Decimal('131.69')),
 ('Cindy', 'Fisher', Decimal('111.73')),
 ('Amanda', 'Carter', Decimal('105.74')),
 ('Christine', 'Roberts', Decimal('89.78')),
 ('Sergio', 'Stanfield', Decimal('102.76')),
 ('Sylvia', 'Ortiz', Decimal('134.70')),
 ('Willard', 'Lumpkin', Decimal('95.79')),
 ('Bernard', 'Colby', Decimal('83.79')),
 ('Brittany', 'Riley', Decimal('151.73')),
 ('Joe', 'Gilliland', Decimal('133.72')),
 ('Evelyn', 'Morgan', Decimal('99.74')),
 ('Ruth', 'Martinez', Decimal('98.82')),
 ('Erin', 'Dunn', Decimal('106.73')),
 ('Leslie', 'Seward', Decimal('123.72')),
 ('Milton', 'Howland', Decimal('121.77')),
 ('Glenda', 'Frazier', Decimal('128.71')),
 ('Keith', 'Rico', Decimal('80.77')),
 ('Eric', 'Robert', Decimal('105.78')),
 ('Austin', 'Cintron', Decimal('78.82')),
 ('Nora', 'Herrera', Decimal('113.74')),
 ('Kenneth', 'Gooden', Decimal('67.86')),
 ('Joseph', 'Joy', Decimal('92.80')),
 ('Brandon', 'Huey', Decimal('145.64')),
 ('Lois', 'Butler', Decimal('107.66')),
 ('Richard', 'Mccrary', Decimal('87.80')),
 ('Teresa', 'Rogers', Decimal('114.74')),
 ('Angela', 'Hernandez', Decimal('138.65')),
 ('Barbara', 'Jones', Decimal('81.78')),
 ('Ana', 'Bradley', Decimal('167.67')),
 ('Diana', 'Alexander', Decimal('105.73')),
 ('Leo', 'Ebert', Decimal('101.78')),
 ('Vicki', 'Fields', Decimal('91.78')),
 ('Dorothy', 'Taylor', Decimal('94.76')),
 ('Virginia', 'Green', Decimal('118.70')),
 ('Florence', 'Woods', Decimal('114.72')),
 ('Jennifer', 'Davis', Decimal('84.75')),
 ('Theodore', 'Culp', Decimal('109.72')),
 ('Charlene', 'Alvarez', Decimal('109.75')),
 ('Jacqueline', 'Long', Decimal('146.68')),
 ('Bryan', 'Hardison', Decimal('105.76')),
 ('Willie', 'Howell', Decimal('100.75')),
 ('Heidi', 'Larson', Decimal('110.68')),
 ('Annette', 'Olson', Decimal('98.76')),
 ('Roy', 'Whiting', Decimal('139.72')),
 ('Enrique', 'Forsythe', Decimal('73.78')),
 ('Miriam', 'Mckinney', Decimal('117.77')),
 ('Diane', 'Collins', Decimal('144.70')),
 ('Georgia', 'Jacobs', Decimal('88.77')),
 ('Janice', 'Ward', Decimal('139.67')),
 ('Patrick', 'Newsom', Decimal('83.77')),
 ('Cecil', 'Vines', Decimal('115.74')),
 ('Harvey', 'Guajardo', Decimal('87.80')),
 ('Gerald', 'Fultz', Decimal('116.71')),
 ('Karen', 'Jackson', Decimal('131.73')),
 ('Clarence', 'Gamez', Decimal('79.75')),
 ('Hector', 'Poindexter', Decimal('119.74')),
 ('Lloyd', 'Dowd', Decimal('66.81')),
 ('Vincent', 'Ralston', Decimal('96.77')),
 ('Patricia', 'Johnson', Decimal('123.74')),
 ('Harry', 'Arce', Decimal('139.69')),
 ('Marian', 'Mendoza', Decimal('76.82')),
 ('Tammy', 'Sanders', Decimal('149.61')),
 ('Marjorie', 'Tucker', Decimal('118.70')),
 ('Lynn', 'Payne', Decimal('121.73')),
 ('Ted', 'Breaux', Decimal('109.73')),
 ('Henry', 'Billingsley', Decimal('64.84')),
 ('Terrence', 'Gunderson', Decimal('110.71')),
 ('April', 'Burns', Decimal('74.77')),
 ('Alicia', 'Mills', Decimal('73.81')),
 ('Christian', 'Jung', Decimal('81.78')),
 ('Curtis', 'Irby', Decimal('167.62')),
 ('Herbert', 'Kruger', Decimal('73.81')),
 ('Terry', 'Grissom', Decimal('68.81')),
 ('Delores', 'Hansen', Decimal('71.84')),
 ('Bobby', 'Boudreau', Decimal('99.68')),
 ('Martha', 'Gonzalez', Decimal('127.66')),
 ('Willie', 'Markham', Decimal('85.78')),
 ('Freddie', 'Duggan', Decimal('87.77')),
 ('Katie', 'Elliott', Decimal('105.77')),
 ('Joann', 'Gardner', Decimal('64.85')),
 ('Allan', 'Cornish', Decimal('63.84')),
 ('Agnes', 'Bishop', Decimal('86.79')),
 ('Calvin', 'Martel', Decimal('111.77')),
 ('Holly', 'Fox', Decimal('111.71')),
 ('Frances', 'Parker', Decimal('92.81')),
 ('Ruben', 'Geary', Decimal('86.81')),
 ('Samantha', 'Duncan', Decimal('71.77')),
 ('Renee', 'Lane', Decimal('92.76')),
 ('Julio', 'Noland', Decimal('84.81')),
 ('Carol', 'Garcia', Decimal('78.81')),
 ('Claude', 'Herzog', Decimal('93.80')),
 ('Tiffany', 'Jordan', Decimal('49.88')),
 ('Lucille', 'Holmes', Decimal('107.73')),
 ('Shirley', 'Allen', Decimal('123.70')),
 ('Leslie', 'Gordon', Decimal('83.80')),
 ('Ken', 'Prewitt', Decimal('99.73')),
 ('Felix', 'Gaffney', Decimal('63.78')),
 ('Tyler', 'Wren', Decimal('82.81')),
 ('Jean', 'Bell', Decimal('105.76')),
 ('Allison', 'Stanley', Decimal('86.75')),
 ('Clyde', 'Tobias', Decimal('112.72')),
 ('Shelly', 'Watts', Decimal('105.77')),
 ('Tamara', 'Nguyen', Decimal('93.75')),
 ('Herman', 'Devore', Decimal('109.72')),
 ('Everett', 'Banda', Decimal('110.72')),
 ('David', 'Royal', Decimal('79.81')),
 ('Julie', 'Sanchez', Decimal('106.72')),
 ('Barry', 'Lovelace', Decimal('121.70')),
 ('Victor', 'Barkley', Decimal('85.78')),
 ('Myrtle', 'Fleming', Decimal('110.76')),
 ('Eugene', 'Culpepper', Decimal('70.82')),
 ('Peter', 'Menard', Decimal('103.78')),
 ('Vernon', 'Chapa', Decimal('81.83')),
 ('Jay', 'Robb', Decimal('85.75')),
 ('Leonard', 'Schofield', Decimal('101.70')),
 ('Sara', 'Perry', Decimal('128.70')),
 ('Beatrice', 'Arnold', Decimal('109.77')),
 ('Laurie', 'Lawrence', Decimal('97.78')),
 ('Brandy', 'Graves', Decimal('94.77')),
 ('Duane', 'Tubbs', Decimal('143.70')),
 ('Peggy', 'Myers', Decimal('86.77')),
 ('Jorge', 'Olivares', Decimal('122.69')),
 ('Judy', 'Gray', Decimal('89.77')),
 ('Carlos', 'Coughlin', Decimal('96.79')),
 ('Anthony', 'Schwab', Decimal('47.85')),
 ('Wendy', 'Harrison', Decimal('86.73')),
 ('Aaron', 'Selby', Decimal('88.80')),
 ('Annie', 'Russell', Decimal('58.82')),
 ('Glenn', 'Pullen', Decimal('88.78')),
 ('Tracy', 'Cole', Decimal('126.72')),
 ('Manuel', 'Murrell', Decimal('103.73')),
 ('Cheryl', 'Murphy', Decimal('119.76')),
 ('Tracy', 'Herrmann', Decimal('118.75')),
 ('Elaine', 'Stevens', Decimal('105.78')),
 ('Dwight', 'Lombardi', Decimal('74.83')),
 ('Arnold', 'Havens', Decimal('161.68')),
 ('Frank', 'Waggoner', Decimal('98.77')),
 ('Alfredo', 'Mcadams', Decimal('85.80')),
 ('Marie', 'Turner', Decimal('101.79')),
 ('Lisa', 'Anderson', Decimal('99.77')),
 ('Isaac', 'Oglesby', Decimal('109.76')),
 ('Tony', 'Carranza', Decimal('62.81')),
 ('Suzanne', 'Nichols', Decimal('94.76')),
 ('Dianne', 'Shelton', Decimal('114.76')),
 ('Edgar', 'Rhoads', Decimal('89.77')),
 ('Kristin', 'Johnston', Decimal('103.74')),
 ('Margaret', 'Moore', Decimal('78.80')),
 ('Chad', 'Carbone', Decimal('86.76')),
 ('Lance', 'Pemberton', Decimal('73.80')),
 ('Jaime', 'Nettles', Decimal('118.73')),
 ('Casey', 'Mena', Decimal('130.68')),
 ('Clayton', 'Barbee', Decimal('75.79')),
 ('Neil', 'Renner', Decimal('149.69')),
 ('Anne', 'Powell', Decimal('72.79')),
 ('Bill', 'Gavin', Decimal('106.73')),
 ('Terrance', 'Roush', Decimal('111.71')),
 ('Leona', 'Obrien', Decimal('32.90')),
 ('Paula', 'Bryant', Decimal('72.83')),
 ('Lena', 'Jensen', Decimal('154.70')),
 ('Max', 'Pitt', Decimal('102.77')),
 ('Ron', 'Deluca', Decimal('99.78')),
 ('Michael', 'Silverman', Decimal('113.74')),
 ('Bernice', 'Willis', Decimal('133.70')),
 ('Rodney', 'Moeller', Decimal('97.78')),
 ('Melissa', 'King', Decimal('123.66')),
 ('Bobbie', 'Craig', Decimal('52.81')),
 ('Michelle', 'Clark', Decimal('146.68')),
 ('Roland', 'South', Decimal('80.77')),
 ('Linda', 'Williams', Decimal('130.76')),
 ('Gary', 'Coy', Decimal('95.78')),
 ('Dora', 'Medina', Decimal('88.81')),
 ('Antonio', 'Meek', Decimal('73.85')),
 ('Irma', 'Pearson', Decimal('70.82')),
 ('Craig', 'Morrell', Decimal('114.72')),
 ('Lorraine', 'Stephens', Decimal('81.80')),
 ('Gloria', 'Cook', Decimal('115.74')),
 ('Megan', 'Palmer', Decimal('81.75')),
 ('Ramona', 'Hale', Decimal('103.77')),
 ('Tonya', 'Chapman', Decimal('147.71')),
 ('Denise', 'Kelly', Decimal('96.74')),
 ('Hazel', 'Warren', Decimal('106.68')),
 ('Rebecca', 'Scott', Decimal('89.76')),
 ('Jeff', 'East', Decimal('107.70')),
 ('Courtney', 'Day', Decimal('103.74')),
 ('Eileen', 'Carr', Decimal('80.82')),
 ('Kelly', 'Torres', Decimal('86.80')),
 ('Dale', 'Ratcliff', Decimal('104.74')),
 ('Timothy', 'Bunn', Decimal('72.82')),
 ('Ruby', 'Washington', Decimal('110.72')),
 ('Francisco', 'Skidmore', Decimal('93.79')),
 ('Jesse', 'Schilling', Decimal('79.78')),
 ('Roberto', 'Vu', Decimal('128.73')),
 ('Raymond', 'Mcwhorter', Decimal('108.75')),
 ('Clara', 'Shaw', Decimal('189.60')),
 ('Jimmie', 'Eggleston', Decimal('135.72')),
 ('Tyrone', 'Asher', Decimal('112.76')),
 ('Debra', 'Nelson', Decimal('141.71')),
 ('Regina', 'Berry', Decimal('129.68')),
 ('Wade', 'Delvalle', Decimal('83.78')),
 ('Dean', 'Sauer', Decimal('106.74')),
 ('Karl', 'Seal', Decimal('208.58')),
 ('Philip', 'Causey', Decimal('115.71')),
 ('Becky', 'Miles', Decimal('80.78')),
 ('Jared', 'Ely', Decimal('81.83')),
 ('Jerome', 'Kenyon', Decimal('67.86')),
 ('Mark', 'Rinehart', Decimal('81.80')),
 ('Sally', 'Pierce', Decimal('108.71')),
 ('Gene', 'Sanborn', Decimal('82.76')),
 ('Olga', 'Jimenez', Decimal('108.76')),
 ('Kristina', 'Chambers', Decimal('80.78')),
 ('Ramon', 'Choate', Decimal('135.70')),
 ('Wesley', 'Bull', Decimal('158.65')),
 ('John', 'Farnsworth', Decimal('123.74')),
 ('Kim', 'Cruz', Decimal('76.80')),
 ('Edward', 'Baugh', Decimal('96.76')),
 ('Sonia', 'Gregory', Decimal('108.78')),
 ('Harold', 'Martino', Decimal('130.68')),
 ('Shane', 'Millard', Decimal('95.78')),
 ('Ellen', 'Simpson', Decimal('102.75')),
 ('Kristen', 'Chavez', Decimal('74.84')),
 ('Ralph', 'Madrigal', Decimal('144.68')),
 ('Darrell', 'Power', Decimal('89.76')),
 ('Emily', 'Diaz', Decimal('90.77')),
 ('Derrick', 'Bourque', Decimal('87.80')),
 ('Adam', 'Gooch', Decimal('97.80')),
 ('Jeremy', 'Hurtado', Decimal('98.75')),
 ('Marion', 'Ocampo', Decimal('107.73')),
 ('Stephanie', 'Mitchell', Decimal('118.75')),
 ('Catherine', 'Campbell', Decimal('131.69')),
 ('Terri', 'Vasquez', Decimal('126.73')),
 ('Alexander', 'Fennell', Decimal('137.67')),
 ('Pearl', 'Garza', Decimal('76.78')),
 ('Kirk', 'Stclair', Decimal('50.83')),
 ('Heather', 'Morris', Decimal('88.76')),
 ('Amy', 'Lopez', Decimal('112.74')),
 ('Sidney', 'Burleson', Decimal('100.76')),
 ('Joshua', 'Mark', Decimal('93.78')),
 ('Brian', 'Wyman', Decimal('27.93')),
 ('Carole', 'Barnett', Decimal('92.75')),
 ('Stella', 'Moreno', Decimal('88.81')),
 ('Christy', 'Vargas', Decimal('113.70')),
 ('Alfred', 'Casillas', Decimal('120.74')),
 ('Anita', 'Morales', Decimal('59.86')),
 ('Amber', 'Dixon', Decimal('113.73')),
 ('Leroy', 'Bustamante', Decimal('104.71')),
 ('Justin', 'Ngo', Decimal('125.67')),
 ('Nancy', 'Thomas', Decimal('93.74')),
 ('Rene', 'Mcalister', Decimal('101.76')),
 ('Zachary', 'Hite', Decimal('134.71')),
 ('Mae', 'Fletcher', Decimal('107.79')),
 ('Norman', 'Currier', Decimal('73.76')),
 ('Francis', 'Sikes', Decimal('98.75')),
 ('Charlie', 'Bess', Decimal('110.76')),
 ('Michele', 'Grant', Decimal('110.73')),
 ('Claudia', 'Fuller', Decimal('106.75')),
 ('Steven', 'Curley', Decimal('80.81')),
 ('Dustin', 'Gillette', Decimal('92.75')),
 ('Mike', 'Way', Decimal('162.67')),
 ('Mabel', 'Holland', Decimal('97.75')),
 ('Stephen', 'Qualls', Decimal('107.74')),
 ('Anna', 'Hill', Decimal('88.80')),
 ('Melvin', 'Ellington', Decimal('96.75')),
 ('Nelson', 'Christenson', Decimal('62.84')),
 ('Gwendolyn', 'May', Decimal('98.75')),
 ('Roberta', 'Harper', Decimal('79.80')),
 ('Jessie', 'Banks', Decimal('81.76')),
 ('Russell', 'Brinson', Decimal('132.65')),
 ('Charlotte', 'Hunter', Decimal('87.78')),
 ('Leah', 'Curtis', Decimal('75.81')),
 ('Sarah', 'Lewis', Decimal('106.73')),
 ('Glen', 'Talbert', Decimal('100.77')),
 ('Ricky', 'Shelby', Decimal('78.77')),
 ('Ernest', 'Stepp', Decimal('77.79')),
 ('Jack', 'Foust', Decimal('87.77')),
 ('Victoria', 'Gibson', Decimal('106.74')),
 ('Hugh', 'Waldrop', Decimal('89.80')),
 ('George', 'Linton', Decimal('113.71')),
 ('Todd', 'Tan', Decimal('109.72')),
 ('Joel', 'Francisco', Decimal('92.78')),
 ('Bradley', 'Motley', Decimal('125.74')),
 ('Don', 'Bone', Decimal('113.77')),
 ('Benjamin', 'Varney', Decimal('89.78')),
 ('Rick', 'Mattox', Decimal('120.75')),
 ('Warren', 'Sherrod', Decimal('152.69')),
 ('James', 'Gannon', Decimal('84.79')),
 ('Erica', 'Matthews', Decimal('86.80')),
 ('Tina', 'Simmons', Decimal('122.74')),
 ('Carl', 'Artis', Decimal('104.79')),
 ('Darren', 'Windham', Decimal('95.78')),
 ('Troy', 'Quigley', Decimal('126.73')),
 ('Stacy', 'Cunningham', Decimal('95.78')),
 ('Randall', 'Neumann', Decimal('85.80')),
 ('Marcia', 'Dean', Decimal('166.61')),
 ('Hilda', 'Hopkins', Decimal('116.73')),
 ('Sue', 'Peters', Decimal('133.68')),
 ('Juanita', 'Mason', Decimal('100.72')),
 ('Brent', 'Harkins', Decimal('104.78')),
 ('Gordon', 'Allard', Decimal('157.69')),
 ('Alex', 'Gresham', Decimal('143.68')),
 ('Maurice', 'Crawley', Decimal('125.74')),
 ('Colleen', 'Burton', Decimal('78.78')),
 ('Reginald', 'Kinder', Decimal('96.75')),
 ('Valerie', 'Black', Decimal('116.75')),
 ('Lewis', 'Lyman', Decimal('86.81')),
 ('Paul', 'Trout', Decimal('80.85')),
 ('Beverly', 'Brooks', Decimal('89.78')),
 ('Clifton', 'Malcolm', Decimal('111.74')),
 ('Gladys', 'Hamilton', Decimal('128.71')),
 ('Rafael', 'Abney', Decimal('91.81')),
 ('Tracey', 'Barrett', Decimal('103.77')),
 ('Minnie', 'Romero', Decimal('108.72')),
 ('Josephine', 'Gomez', Decimal('104.75')),
 ('Bonnie', 'Hughes', Decimal('84.80')),
 ('Jacob', 'Lance', Decimal('74.80')),
 ('Melanie', 'Armstrong', Decimal('92.75')),
 ('Derek', 'Blakely', Decimal('90.73')),
 ('Marlene', 'Welch', Decimal('106.77')),
 ('Ian', 'Still', Decimal('86.75')),
 ('Jeffrey', 'Spear', Decimal('65.83')),
 ('Adrian', 'Clary', Decimal('68.82')),
 ('Alma', 'Austin', Decimal('128.69')),
 ('Toni', 'Holt', Decimal('73.83')),
 ('Helen', 'Harris', Decimal('134.68')),
 ('Maureen', 'Little', Decimal('87.79')),
 ('Ella', 'Oliver', Decimal('134.70')),
 ('Ann', 'Evans', Decimal('67.86')),
 ('Clifford', 'Bowens', Decimal('109.73')),
 ('Erika', 'Pena', Decimal('78.79')),
 ('Katherine', 'Rivera', Decimal('57.87')),
 ('Andrea', 'Henderson', Decimal('92.79')),
 ('Viola', 'Hanson', Decimal('122.70')),
 ('Tim', 'Cary', Decimal('154.66')),
 ('Vickie', 'Brewer', Decimal('100.75')),
 ('Rosemary', 'Schmidt', Decimal('134.69')),
 ('Rita', 'Graham', Decimal('77.78')),
 ('Elizabeth', 'Brown', Decimal('134.65')),
 ('Dolores', 'Wagner', Decimal('104.75')),
 ('Ronnie', 'Ricketts', Decimal('95.76')),
 ('Jimmy', 'Schrader', Decimal('104.72')),
 ('Jamie', 'Waugh', Decimal('110.77')),
 ('Jesus', 'Mccartney', Decimal('107.77')),
 ('Felicia', 'Sutton', Decimal('68.77')),
 ('Ryan', 'Salisbury', Decimal('142.70')),
 ('Dana', 'Hart', Decimal('120.74')),
 ('Kelly', 'Knott', Decimal('94.76')),
 ('Wallace', 'Slone', Decimal('97.78')),
 ('Sherri', 'Rhodes', Decimal('99.74')),
 ('Kevin', 'Schuler', Decimal('93.83')),
 ('Lawrence', 'Lawton', Decimal('89.71')),
 ('William', 'Satterfield', Decimal('70.81')),
 ('Dawn', 'Sullivan', Decimal('93.78')),
 ('Luis', 'Yanez', Decimal('77.81')),
 ('Greg', 'Robins', Decimal('131.74')),
 ('Marcus', 'Hidalgo', Decimal('105.72')),
 ('Micheal', 'Forman', Decimal('96.76')),
 ('Lillie', 'Kim', Decimal('89.77')),
 ('Clinton', 'Buford', Decimal('98.76')),
 ('Phyllis', 'Foster', Decimal('76.80')),
 ('Julia', 'Flores', Decimal('124.71')),
 ('Louis', 'Leone', Decimal('156.66')),
 ('Mattie', 'Hoffman', Decimal('58.80')),
 ('Brenda', 'Wright', Decimal('104.74')),
 ('Douglas', 'Graf', Decimal('106.77')),
 ('Alvin', 'Deloach', Decimal('134.72')),
 ('Larry', 'Thrasher', Decimal('74.81')),
 ('Terry', 'Carlson', Decimal('116.74')),
 ('Betty', 'White', Decimal('96.77')),
 ('Virgil', 'Wofford', Decimal('97.75')),
 ('Edna', 'West', Decimal('79.81')),
 ('Gilbert', 'Sledge', Decimal('121.73')),
 ('Gail', 'Knight', Decimal('106.76')),
 ('Pauline', 'Henry', Decimal('88.75')),
 ('Jeffery', 'Pinson', Decimal('113.72')),
 ('Vanessa', 'Sims', Decimal('86.81')),
 ('Beth', 'Franklin', Decimal('95.76')),
 ('Steve', 'Mackenzie', Decimal('152.68')),
 ('Fred', 'Wheat', Decimal('69.79')),
 ('Mario', 'Cheatham', Decimal('107.73')),
 ('Walter', 'Perryman', Decimal('95.76')),
 ('Lydia', 'Burke', Decimal('77.77')),
 ('Gregory', 'Mauldin', Decimal('73.78')),
 ('Kent', 'Arsenault', Decimal('134.73')),
 ('Martin', 'Bales', Decimal('93.75')),
 ('Joy', 'George', Decimal('118.69')),
 ('Robert', 'Baughman', Decimal('71.85')),
 ('Maria', 'Miller', Decimal('130.72')),
 ('Maxine', 'Silva', Decimal('107.70')),
 ('Angel', 'Barclay', Decimal('99.72')),
 ('Howard', 'Fortner', Decimal('93.74')),
 ('Lori', 'Wood', Decimal('141.69')),
 ('Byron', 'Box', Decimal('117.72')),
 ('Jill', 'Hawkins', Decimal('58.83')),
 ('Jo', 'Fowler', Decimal('54.85')),
 ('Edwin', 'Burk', Decimal('93.80')),
 ('Sharon', 'Robinson', Decimal('103.73')),
 ('Ronald', 'Weiner', Decimal('93.79')),
 ('Mary', 'Smith', Decimal('114.70')),
 ('Irene', 'Price', Decimal('74.79')),
 ('Connie', 'Wallace', Decimal('95.79')),
 ('Brad', 'Mccurdy', Decimal('100.76')),
 ('Marion', 'Snyder', Decimal('194.61')),
 ('Carrie', 'Porter', Decimal('124.66')),
 ('Tara', 'Ryan', Decimal('87.81')),
 ('Susan', 'Wilson', Decimal('85.77')),
 ('Perry', 'Swafford', Decimal('117.76')),
 ('Jon', 'Wiles', Decimal('85.78')),
 ('Arthur', 'Simpkins', Decimal('145.70')),
 ('Kathy', 'James', Decimal('116.72')),
 ('Wayne', 'Truong', Decimal('70.81')),
 ('Margie', 'Wade', Decimal('142.67')),
 ('Nicole', 'Peterson', Decimal('94.78')),
 ('Miguel', 'Betancourt', Decimal('127.73')),
 ('Jamie', 'Rice', Decimal('126.73')),
 ('Marilyn', 'Ross', Decimal('137.70')),
 ('Earl', 'Shanks', Decimal('105.74')),
 ('Lauren', 'Hudson', Decimal('59.83')),
 ('Chester', 'Benner', Decimal('92.78')),
 ('Esther', 'Crawford', Decimal('95.72')),
 ('Franklin', 'Troutman', Decimal('69.79')),
 ('Jason', 'Morrissey', Decimal('81.81')),
 ('Andy', 'Vanhorn', Decimal('112.76')),
 ('Alan', 'Kahn', Decimal('119.75')),
 ('Scott', 'Shelley', Decimal('60.82')),
 ('Tanya', 'Gilbert', Decimal('138.69')),
 ('Patsy', 'Davidson', Decimal('114.73')),
 ('Jim', 'Rea', Decimal('121.70')),
 ('Matthew', 'Mahan', Decimal('91.75')),
 ('Jerry', 'Jordon', Decimal('111.76')),
 ('Roger', 'Quintanilla', Decimal('144.66')),
 ('Grace', 'Ellis', Decimal('126.70')),
 ('Mildred', 'Bailey', Decimal('88.78')),
 ('Nathaniel', 'Adam', Decimal('117.75')),
 ('Nellie', 'Garrett', Decimal('86.81')),
 ('Danny', 'Isom', Decimal('73.82')),
 ('Rosa', 'Reynolds', Decimal('129.72')),
 ('Jordan', 'Archuleta', Decimal('129.71')),
 ('Kurt', 'Emmons', Decimal('87.80')),
 ('Violet', 'Rodriquez', Decimal('104.76')),
 ('Nina', 'Soto', Decimal('96.79')),
 ('Gabriel', 'Harder', Decimal('108.75')),
 ('Rose', 'Howard', Decimal('97.80')),
 ('Marshall', 'Thorn', Decimal('117.77')),
 ('Dave', 'Gardiner', Decimal('113.73')),
 ('Sheila', 'Wells', Decimal('57.86')),

In [ ]:
#5. **¿Cuál es el pago total más alto realizado?**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  payment_id, amount 
FROM
  payment
order by 2 desc
limit 15;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(28814, Decimal('11.99')),
 (24553, Decimal('11.99')),
 (23757, Decimal('11.99')),
 (28799, Decimal('11.99')),
 (29136, Decimal('11.99')),
 (24866, Decimal('11.99')),
 (20403, Decimal('11.99')),
 (22650, Decimal('11.99')),
 (19481, Decimal('10.99')),
 (18153, Decimal('10.99')),
 (18640, Decimal('10.99')),
 (18576, Decimal('10.99')),
 (18035, Decimal('10.99')),
 (19336, Decimal('10.99')),
 (19642, Decimal('10.99'))]

In [ ]:
#**6. ¿Cuál es el nombre del cliente que realizó los pagos totales más altos?**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 payment.customer_id, customer.first_name, payment.amount 
FROM
  payment
JOIN
  rental
ON
WHERE
  amount = 
  (SELECT
    MAX(amount)
    FROM
    payment
  );
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(362, Decimal('11.99')),
 (204, Decimal('11.99')),
 (116, Decimal('11.99')),
 (195, Decimal('11.99')),
 (237, Decimal('11.99')),
 (591, Decimal('11.99')),
 (592, Decimal('11.99')),
 (13, Decimal('11.99'))]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 customer.first_name, customer.last_name, payment.amount 
FROM
  payment
JOIN
  customer
ON
  payment.customer_id=customer.customer_id
WHERE
  amount = 
  (SELECT
    MAX(payment.amount)
    FROM
    payment
  );
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Nicholas', 'Barfield', Decimal('11.99')),
 ('Rosemary', 'Schmidt', Decimal('11.99')),
 ('Victoria', 'Gibson', Decimal('11.99')),
 ('Vanessa', 'Sims', Decimal('11.99')),
 ('Tanya', 'Gilbert', Decimal('11.99')),
 ('Kent', 'Arsenault', Decimal('11.99')),
 ('Terrance', 'Roush', Decimal('11.99')),
 ('Karen', 'Jackson', Decimal('11.99'))]

In [ ]:
#**7. ¿Cuáles son las películas que más se alquilaron?**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.title, COUNT(rental.rental_id )
FROM
  rental
JOIN
  inventory
ON
  rental.inventory_id = inventory.inventory_id
JOIN
  film
ON
  film.film_id = inventory.film_id
GROUP BY
  1
ORDER BY 
  2 DESC
LIMIT (10);
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Bucket Brotherhood', 34),
 ('Rocketeer Mother', 33),
 ('Juggler Hardly', 32),
 ('Ridgemont Submarine', 32),
 ('Grit Clockwork', 32),
 ('Forward Temple', 32),
 ('Scalawag Duck', 32),
 ('Apache Divine', 31),
 ('Goodfellas Salute', 31),
 ('Rush Goodfellas', 31)]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 inventory.film_id, COUNT(rental.rental_id )
FROM
  rental
JOIN
  inventory
ON
  rental.inventory_id = inventory.inventory_id
GROUP BY
  1
ORDER BY 
  2 DESC
LIMIT (10);
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(103, 34),
 (738, 33),
 (730, 32),
 (489, 32),
 (331, 32),
 (767, 32),
 (382, 32),
 (735, 31),
 (418, 31),
 (891, 31),
 (31, 31)]

In [ ]:
#**8. Qué películas se han alquilado hasta ahora.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.title, COUNT(rental.rental_id)
FROM
  film
JOIN
  inventory
ON
  film.film_id = inventory.film_id
JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
GROUP BY
  1
ORDER BY
2 ASC;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
print(result)
print(len(result))

[('Mixed Doors', 4), ('Train Bunch', 4), ('Hardly Robbers', 4), ('Mannequin Worst', 5), ('Braveheart Human', 5), ('Bunch Minds', 5), ('Private Drop', 5), ('Traffic Hobbit', 5), ('Mussolini Spoilers', 5), ('Seven Swarm', 5), ('Full Flatliners', 5), ('Fever Empire', 5), ('Glory Tracy', 5), ('Informer Double', 5), ('Conspiracy Spirit', 5), ('Freedom Cleopatra', 5), ('Hunter Alter', 5), ('Graceland Dynamite', 6), ('Terminator Club', 6), ('Extraordinary Conquerer', 6), ('Oklahoma Jumanji', 6), ('Rushmore Mermaid', 6), ('Tequila Past', 6), ('School Jacket', 6), ('Happiness United', 6), ('Frontier Cabin', 6), ('Sling Luke', 6), ('Apocalypse Flamingos', 6), ('Watership Frontier', 6), ('Ladybugs Armageddon', 6), ('Bed Highball', 6), ('Simon North', 6), ('Texas Watch', 6), ('Bubble Grosse', 6), ('Jersey Sassy', 6), ('Haunted Antitrust', 6), ('Wild Apollo', 6), ('Duck Racer', 6), ('Comancheros Enemy', 6), ('Italian African', 6), ('Warlock Werewolf', 6), ('Desperate Trainspotting', 6), ('Killer Innocent', 6), ('Japanese Run', 6), ('Youth Kick', 6), ('Phantom Glory', 6), ('Cassidy Wyoming', 6), ('Dumbo Lust', 6), ('Clerks Angels', 7), ('Ishtar Rocketeer', 7), ('Doctor Grail', 7), ('Ace Goldfinger', 7), ('Control Anthem', 7), ('Sense Greek', 7), ('Treatment Jekyll', 7), ('Leathernecks Dwarfs', 7), ('Connection Microcosmos', 7), ('Newsies Story', 7), ('Clue Grail', 7), ('Pizza Jumanji', 7), ('Luke Mummy', 7), ('Bang Kwai', 7), ('Vanished Garden', 7), ('Early Home', 7), ('Panic Club', 7), ('President Bang', 7), ('Divorce Shining', 7), ('Duffel Apocalypse', 7), ('Cowboy Doom', 7), ('Cruelty Unforgiven', 7), ('Dozen Lion', 7), ('Stallion Sundance', 7), ('Magic Mallrats', 7), ('Squad Fish', 7), ('Young Language', 7), ('Lesson Cleopatra', 7), ('Hawk Chill', 7), ('Bulworth Commandments', 7), ('Eve Resurrection', 7), ('Mulholland Beast', 7), ('Fire Wolves', 7), ('Elf Murder', 7), ('Heavenly Gun', 7), ('Menagerie Rushmore', 7), ('License Weekend', 7), ('Vision Torque', 7), ('Records Zorro', 8), ('Park Citizen', 8), ('Clyde Theory', 8), ('Crusade Honey', 8), ('Gosford Donnie', 8), ('Maude Mod', 8), ('Destination Jerk', 8), ('Soup Wisdom', 8), ('Magnificent Chitty', 8), ('Jumanji Blade', 8), ('Untouchables Sunrise', 8), ('Tarzan Videotape', 8), ('World Leathernecks', 8), ('Lights Deer', 8), ('Casper Dragonfly', 8), ('Hoosiers Birdcage', 8), ('Godfather Diary', 8), ('Papi Necklace', 8), ('Saints Bride', 8), ('Punk Divorce', 8), ('Harold French', 8), ('Chaplin License', 8), ('Desire Alien', 8), ('Grosse Wonderful', 8), ('Unfaithful Kill', 8), ('Shining Roses', 8), ('Baby Hall', 8), ('Vertigo Northwest', 8), ('Pet Haunting', 8), ('Runner Madigan', 8), ('Chitty Lock', 8), ('Ballroom Mockingbird', 8), ('Soldiers Evolution', 8), ('Rebel Airport', 8), ('Sunset Racer', 8), ('Runaway Tenenbaums', 8), ('Dolls Rage', 9), ('Dwarfs Alter', 9), ('Maguire Apache', 9), ('Kramer Chocolate', 9), ('Miracle Virtual', 9), ('Gilbert Pelican', 9), ('Drop Waterfront', 9), ('Birdcage Casper', 9), ('Legally Secretary', 9), ('Dares Pluto', 9), ('Caribbean Liberty', 9), ('Ghostbusters Elf', 9), ('Victory Academy', 9), ('Snatchers Montezuma', 9), ('Casualties Encino', 9), ('Spartacus Cheaper', 9), ('Crazy Home', 9), ('Wisdom Worker', 9), ('Ali Forever', 9), ('Darling Breaking', 9), ('Hotel Happiness', 9), ('Nuts Ties', 9), ('Jungle Closer', 9), ('Diary Panic', 9), ('Vanilla Day', 9), ('Random Go', 9), ('Montezuma Command', 9), ('Intolerable Intentions', 9), ('Impact Aladdin', 9), ('Anything Savannah', 9), ('King Evolution', 9), ('Legend Jedi', 9), ('Zhivago Core', 9), ('Frisco Forrest', 9), ('Reds Pocus', 9), ('Monsoon Cause', 9), ('Holy Tadpole', 9), ('Speed Suit', 9), ('Daughter Madigan', 9), ('Won Dares', 9), ('Wonderful Drop', 9), ('Guys Falcon', 9), ('Platoon Instinct', 9), ('Matrix Snowman', 9), ('Element Freddy', 10), ('Oleander Clue', 10), ('Gone Trouble', 10), ('Lambs Cincinatti', 10), ('Frogmen Breaking', 10), ('Beneath Rush', 10), ('Spoilers Hellfighters', 10), ('Blood Argonauts', 10), ('Grail Frankenstein', 10), ('Madigan Dorado', 10), ('Doubtfire Labyrinth', 10), ('Antitrust Tomatoes', 10), ('Paths Control', 10), ('Amelie Hellfighters', 10), ('Clockwork Paradise', 10), ('Wars Pluto', 10), ('Jawbreaker Brooklyn', 10), ('Hollow Jeopardy', 10), ('Stage World', 10), ('Notting Speakeasy', 10), ('Lolita World', 10), ('Jeopardy Encino', 10), ('Smile Earring', 10), ('Sensibility Rear', 10), ('Wagon Jaws', 10), ('Maker Gables', 10), ('Right Cranes', 10), ('Run Pacific', 10), ('Fiddler Lost', 10), ('Life Twisted', 10), ('Superfly Trip', 10), ('Lover Truman', 10), ('Halloween Nuts', 10), ('Reservoir Adaptation', 10), ('Mystic Truman', 10), ('Elizabeth Shane', 10), ('Luck Opus', 10), ('Rollercoaster Bringing', 10), ('Prix Undefeated', 11), ('Ties Hunger', 11), ('Language Cowboy', 11), ('Iron Moon', 11), ('Frida Slipper', 11), ('Ending Crowds', 11), ('Bowfinger Gables', 11), ('Stranger Strangers', 11), ('Potluck Mixed', 11), ('Towers Hurricane', 11), ('Birch Antitrust', 11), ('Cranes Reservoir', 11), ('Reef Salute', 11), ('Gathering Calendar', 11), ('Thin Sagebrush', 11), ('Rider Caddyshack', 11), ('Twisted Pirates', 11), ('Beast Hunchback', 11), ('Bird Independence', 11), ('Magnolia Forrester', 11), ('Spirited Casualties', 11), ('Beethoven Exorcist', 11), ('Bugsy Song', 11), ('Mod Secretary', 11), ('North Tequila', 11), ('Stone Fire', 11), ('Trainspotting Strangers', 11), ('Lord Arizona', 11), ('Feathers Metal', 11), ('Autumn Crow', 11), ('Santa Paris', 11), ('Drumline Cyclone', 11), ('Song Hedwig', 11), ('Fugitive Maguire', 11), ('Darko Dorado', 11), ('Opus Ice', 11), ('Dragon Squad', 11), ('October Submarine', 11), ('Theory Mermaid', 11), ('Silverado Goldfinger', 12), ('Vampire Whale', 12), ('Crow Grease', 12), ('Savannah Town', 12), ('Meet Chocolate', 12), ('Smoochy Control', 12), ('African Egg', 12), ('Massage Image', 12), ('Minority Kiss', 12), ('Speakeasy Date', 12), ('Mighty Luck', 12), ('Gunfighter Mussolini', 12), ('Uptown Young', 12), ('Dangerous Uptown', 12), ('Tycoon Gathering', 12), ('Adaptation Holes', 12), ('Loverboy Attacks', 12), ('Evolution Alter', 12), ('Blanket Beverly', 12), ('War Notting', 12), ('Finding Anaconda', 12), ('Lost Bird', 12), ('Alabama Devil', 12), ('Liberty Magnificent', 12), ('Sorority Queen', 12), ('Side Ark', 12), ('Flight Lies', 12), ('Temple Attraction', 12), ('California Birds', 12), ('Mob Duffel', 12), ('Hedwig Alter', 12), ('Pittsburgh Hunchback', 12), ('Born Spinal', 12), ('Brannigan Sunrise', 12), ('Valentine Vanishing', 12), ('Window Side', 12), ('Chamber Italian', 13), ('Bright Encounters', 13), ('Breaking Home', 13), ('Tuxedo Mile', 13), ('Past Suicides', 13), ('Flash Wars', 13), ('Exorcist Sting', 13), ('Super Wyoming', 13), ('Cincinatti Whisperer', 13), ('Hollywood Anonymous', 13), ('Mulan Moon', 13), ('Hook Chariots', 13), ('Wyoming Storm', 13), ('Behavior Runaway', 13), ('Natural Stock', 13), ('Mile Mulan', 13), ('Bilko Anonymous', 13), ('Opposite Necklace', 13), ('Spinal Rocky', 13), ('Memento Zoolander', 13), ('Sassy Packer', 13), ('Spiking Element', 13), ('Monterey Labyrinth', 13), ('Chisum Behavior', 13), ('Darkness War', 13), ('Saturn Name', 13), ('Microcosmos Paradise', 13), ('Date Speed', 13), ('Express Lonely', 13), ('Lucky Flying', 13), ('Anonymous Human', 13), ('Tenenbaums Command', 13), ('Forever Candidate', 13), ('Robbery Bright', 13), ('Raging Airplane', 13), ('Purple Movie', 13), ('Drums Dynamite', 13), ('State Wasteland', 13), ('Usual Untouchables', 13), ('Jingle Sagebrush', 13), ('Lawrence Love', 13), ('Moonwalker Fool', 13), ('Party Knock', 13), ('Citizen Shrek', 13), ('Bedazzled Married', 13), ('Champion Flatliners', 13), ('Everyone Craft', 13), ('Hunger Roof', 13), ('Connecticut Tramp', 13), ('Identity Lover', 13), ('Daddy Pittsburgh', 13), ('Arabia Dogma', 13), ('Alley Evolution', 14), ('Kane Exorcist', 14), ('Splash Gump', 14), ('Blindness Gun', 14), ('Jaws Harry', 14), ('Stampede Disturbing', 14), ('Donnie Alley', 14), ('Town Ark', 14), ('Confessions Maguire', 14), ('Troopers Metal', 14), ('Image Princess', 14), ('Nemo Campus', 14), ('Pajama Jawbreaker', 14), ('Elephant Trojan', 14), ('Uncut Suicides', 14), ('Day Unfaithful', 14), ('Virtual Spoilers', 14), ('Searchers Wait', 14), ('Lovely Jingle', 14), ('Stock Glass', 14), ('Glass Dying', 14), ('Creepers Kane', 14), ('Peach Innocent', 14), ('Werewolf Lola', 14), ('Outlaw Hanky', 14), ('Mother Oleander', 14), ('Impossible Prejudice', 14), ('Analyze Hoosiers', 14), ('Shanghai Tycoon', 14), ('Hamlet Wisdom', 14), ('Turn Star', 14), ('Wrath Mile', 14), ('Shrunk Divine', 14), ('Paris Weekend', 14), ('Personal Ladybugs', 14), ('Grinch Massage', 14), ('Games Bowfinger', 14), ('Greedy Roots', 14), ('Gold River', 14), ('Deep Crusade', 14), ('Home Pity', 14), ('Dances None', 14), ('Shane Darkness', 14), ('Tomatoes Hellfighters', 14), ('Madre Gables', 14), ('Saddle Antitrust', 14), ('Notorious Reunion', 14), ('Human Graffiti', 15), ('Lonely Elephant', 15), ('Worker Tarzan', 15), ('Necklace Outbreak', 15), ('Loser Hustler', 15), ('Entrapment Satisfaction', 15), ('Cyclone Family', 15), ('Cabin Flash', 15), ('Translation Summer', 15), ('Ship Wonderland', 15), ('Nash Chocolat', 15), ('Anthem Luke', 15), ('Shrek License', 15), ('Dirty Ace', 15), ('Scissorhands Slums', 15), ('Boiled Dares', 15), ('Vietnam Smoochy', 15), ('Panther Reds', 15), ('Sons Interview', 15), ('Modern Dorado', 15), ('Sweet Brotherhood', 15), ('Sierra Divide', 15), ('Mosquito Armageddon', 15), ('Spirit Flintstones', 15), ('Odds Boogie', 15), ('Edge Kissing', 15), ('Siege Madre', 15), ('Hunting Musketeers', 15), ('Rings Heartbreakers', 15), ('Divine Resurrection', 15), ('Manchurian Curtain', 15), ('Lust Lock', 15), ('Tootsie Pilot', 15), ('Submarine Bed', 15), ('Airplane Sierra', 15), ('Model Fish', 15), ('Holes Brannigan', 15), ('Valley Packer', 15), ('Hysterical Grail', 15), ('Devil Desire', 15), ('Betrayed Rear', 15), ('Holiday Games', 15), ('Wasteland Divine', 15), ('Labyrinth League', 15), ('Charade Duffel', 15), ('Steers Armageddon', 15), ('Illusion Amelie', 15), ('Panky Submarine', 15), ('Monster Spartacus', 15), ('Madison Trap', 15), ('Circus Youth', 15), ('Jeepers Wedding', 16), ('Wizard Coldblooded', 16), ('Pure Runner', 16), ('Hall Cassidy', 16), ('Wanda Chamber', 16), ('Mummy Creatures', 16), ('Streak Ridgemont', 16), ('Dude Blindness', 16), ('Indian Love', 16), ('Willow Tracy', 16), ('Mermaid Insects', 16), ('Pluto Oleander', 16), ('Bonnie Holocaust', 16), ('Trap Guys', 16), ('Artist Coldblooded', 16), ('Conquerer Nuts', 16), ('Quills Bull', 16), ('Summer Scarface', 16), ('Pickup Driving', 16), ('Uprising Uptown', 16), ('Varsity Trip', 16), ('Graduate Lord', 16), ('Sagebrush Clueless', 16), ('Patriot Roman', 16), ('Attacks Hate', 16), ('Chicago North', 16), ('Caddyshack Jedi', 16), ('Casablanca Super', 16), ('Worst Banger', 16), ('Creatures Shakespeare', 16), ('West Lion', 16), ('Army Flintstones', 16), ('Coldblooded Darling', 16), ('Baked Cleopatra', 16), ('Bull Shawshank', 16), ('Craft Outfield', 16), ('Gaslight Crusade', 16), ('Moulin Wake', 16), ('Destiny Saturday', 16), ('Rules Human', 16), ('Homeward Cider', 16), ('Reap Unfaithful', 16), ('Motions Details', 16), ('Pilot Hoosiers', 16), ('Silence Kane', 16), ('Slipper Fidelity', 16), ('Lock Rear', 16), ('Rocky War', 16), ('Words Hunter', 16), ('Watch Tracy', 16), ('Pride Alamo', 16), ('Command Darling', 16), ('Daisy Menagerie', 16), ('Paycheck Wait', 16), ('Lawless Vision', 17), ('Sugar Wonka', 17), ('Intentions Empire', 17), ('Flintstones Happiness', 17), ('Roots Remember', 17), ('Louisiana Harry', 17), ('Conversation Downhill', 17), ('Musketeers Wait', 17), ('Factory Dragon', 17), ('Jericho Mulan', 17), ('Perfect Groove', 17), ('Teen Apollo', 17), ('Potter Connecticut', 17), ('Newton Labyrinth', 17), ('Idaho Love', 17), ('Majestic Floats', 17), ('Poseidon Forever', 17), ('Breakfast Goldfinger', 17), ('Taxi Kick', 17), ('Satisfaction Confidential', 17), ('Jekyll Frogmen', 17), ('Holocaust Highball', 17), ('Virgin Daisy', 17), ('Mask Peach', 17), ('Dying Maker', 17), ('League Hellfighters', 17), ('Hanover Galaxy', 17), ('Beach Heartbreakers', 17), ('Lady Stage', 17), ('Waterfront Deliverance', 17), ('United Pilot', 17), ('Gandhi Kwai', 17), ('Bikini Borrowers', 17), ('Rear Trading', 17), ('Strangers Graffiti', 17), ('Egypt Tenenbaums', 17), ('Joon Northwest', 17), ('Freaky Pocus', 17), ('Noon Papi', 17), ('Midnight Westward', 17), ('Rock Instinct', 17), ('Zoolander Fiction', 17), ('French Holiday', 17), ('Comforts Rush', 17), ('Confused Candles', 17), ('Orient Closer', 17), ('Greek Everyone', 17), ('Slacker Liaisons', 17), ('Ferris Mother', 17), ('Airport Pollock', 18), ('Dragonfly Strangers', 18), ('Sweden Shining', 18), ('Mission Zoolander', 18), ('Alone Trip', 18), ('Candidate Perdition', 18), ('Whale Bikini', 18), ('Expecations Natural', 18), ('Enough Raging', 18), ('Birds Perdition', 18), ('Hope Tootsie', 18), ('Lion Uncut', 18), ('Barefoot Manchurian', 18), ('Smoking Barbarella', 18), ('Insects Stone', 18), ('Galaxy Sweethearts', 18), ('Core Suit', 18), ('Groundhog Uncut', 18), ('Jacket Frisco', 18), ('Cleopatra Devil', 18), ('Secretary Rouge', 18), ('Instinct Airport', 18), ('Pollock Deliverance', 18), ('Unforgiven Zoolander', 18), ('Scarface Bang', 18), ('Wonka Sea', 18), ('Weekend Personal', 18), ('Vanishing Rocky', 18), ('Inch Jet', 18), ('Driver Annie', 18), ('Rouge Squad', 18), ('Polish Brooklyn', 18), ('Forrest Sons', 18), ('Carol Texas', 18), ('Boulevard Mob', 18), ('Jade Bunch', 18), ('Paradise Sabrina', 18), ('Heaven Freedom', 18), ('Dawn Pond', 18), ('Racer Egg', 18), ('Groove Fiction', 18), ('Remember Diary', 18), ('Darn Forrester', 18), ('Encino Elf', 19), ('Gorgeous Bingo', 19), ('Hanging Deep', 19), ('Bill Others', 19), ('Requiem Tycoon', 19), ('Campus Remember', 19), ('Fantasia Park', 19), ('Cider Desire', 19), ('Pond Seattle', 19), ('Road Roxanne', 19), ('Shawshank Bubble', 19), ('Bride Intrigue', 19), ('Gables Metropolis', 19), ('Independence Hotel', 19), ('Desert Poseidon', 19), ('Mine Titans', 19), ('Voice Peach', 19), ('Mars Roman', 19), ('Patient Sister', 19), ('Fury Murder', 19), ('Roxanne Rebel', 19), ('Encounters Curtain', 19), ('Hours Rage', 19), ('Fiction Christmas', 19), ('Something Duck', 19), ('Trojan Tomorrow', 19), ('Jedi Beneath', 19), ('Thief Pelican', 19), ('Canyon Stock', 19), ('Igby Maker', 19), ('Rage Games', 19), ('National Story', 19), ('Clones Pinocchio', 19), ('Neighbors Charade', 19), ('Sundance Invasion', 19), ('Disciple Mother', 19), ('Club Graffiti', 19), ('Honey Ties', 19), ('Music Boondock', 19), ('Details Packer', 19), ('Novocaine Flight', 19), ('Earring Instinct', 19), ('Backlash Undefeated', 19), ('Doors President', 19), ('Eyes Driving', 19), ('Heartbreakers Bright', 20), ('Harper Dying', 20), ('Masked Bubble', 20), ('Intrigue Worst', 20), ('Million Ace', 20), ('Room Roman', 20), ('Money Harold', 20), ('Outfield Massacre', 20), ('Pinocchio Simon', 20), ('Minds Truman', 20), ('Sleepless Monsoon', 20), ('Garden Island', 20), ('Kick Savannah', 20), ('Tramp Others', 20), ('Cheaper Clyde', 20), ('Northwest Polish', 20), ('Chocolat Harry', 20), ('Love Suicides', 20), ('Bringing Hysterical', 20), ('Secrets Paradise', 20), ('Prejudice Oleander', 20), ('Chasing Fight', 20), ('Peak Forever', 20), ('Straight Hours', 20), ('Stepmom Dream', 20), ('Hellfighters Sierra', 20), ('Reunion Witches', 20), ('Reign Gentlemen', 20), ('Jet Neighbors', 20), ('Kissing Dolls', 20), ('Flying Hook', 20), ('Jerk Paycheck', 20), ('Insider Arizona', 20), ('Dinosaur Secretary', 20), ('Go Purple', 20), ('Spice Sorority', 20), ('Interview Liaisons', 20), ('Dalmations Sweden', 20), ('Redemption Comforts', 20), ('Hunchback Impossible', 20), ('River Outlaw', 20), ('Wrong Behavior', 20), ('Quest Mussolini', 20), ('Splendor Patton', 21), ('Sabrina Midnight', 21), ('Fidelity Devil', 21), ('Amistad Midsummer', 21), ('Star Operation', 21), ('Badman Dawn', 21), ('Unbreakable Karate', 21), ('Wolves Desire', 21), ('Blues Instinct', 21), ('Pianist Outfield', 21), ('Lebowski Soldiers', 21), ('Highball Potter', 21), ('Chariots Conspiracy', 21), ('Pirates Roxanne', 21), ('Coast Rainbow', 21), ('Mourning Purple', 21), ('Amadeus Holy', 21), ('Crossroads Casualties', 21), ('Sting Personal', 21), ('Vacation Boondock', 21), ('Moonshine Cabin', 21), ('Sleuth Orient', 21), ('Divide Monster', 21), ('Chainsaw Uptown', 21), ('Agent Truman', 21), ('Open African', 21), ('Armageddon Lost', 21), ('Secret Groundhog', 21), ('Calendar Gunfight', 21), ('Deceiver Betrayed', 21), ('Christmas Moonshine', 21), ('Beverly Outlaw', 21), ('Doom Dancing', 21), ('Suit Walls', 21), ('Arizona Bang', 21), ('Egg Igby', 21), ('Cause Date', 21), ('Brooklyn Desert', 21), ('Wait Cider', 21), ('Resurrection Silverado', 21), ('Empire Malkovich', 21), ('Anaconda Confessions', 21), ('Undefeated Dalmations', 21), ('Fireball Philadelphia', 21), ('Sleepy Japanese', 21), ('Basic Easy', 21), ('Driving Polish', 21), ('Dracula Crystal', 21), ('Excitement Eve', 21), ('Berets Agent', 21), ('Grease Youth', 21), ('Ghost Groundhog', 21), ('Homicide Peach', 22), ('Maltese Hope', 22), ('South Wait', 22), ('Shakespeare Saddle', 22), ('Dream Pickup', 22), ('Midsummer Groundhog', 22), ('Angels Life', 22), ('American Circus', 22), ('Borrowers Bedazzled', 22), ('Chill Luck', 22), ('Packer Madigan', 22), ('Queen Luke', 22), ('Hustler Party', 22), ('Bear Graceland', 22), ('Tourist Pelican', 22), ('Flatliners Killer', 22), ('Sea Virgin', 22), ('Beauty Grease', 22), ('Banger Pinocchio', 22), ('Eagles Panky', 22), ('High Encino', 22), ('Head Stranger', 22), ('Kiss Glory', 22), ('Blade Polish', 22), ('Fight Jawbreaker', 22), ('Chicken Hellfighters', 22), ('Sinners Atlantis', 22), ('Snatch Slipper', 22), ('Volcano Texas', 22), ('Alter Victory', 22), ('Falcon Volume', 22), ('Wonderland Christmas', 22), ('Liaisons Sweet', 22), ('Congeniality Quest', 22), ('Grapes Fury', 22), ('Whisperer Giant', 22), ('Haunting Pianist', 22), ('Annie Identity', 22), ('Alien Center', 22), ('Strictly Scarface', 23), ('Philadelphia Wife', 23), ('Carrie Bunch', 23), ('Patton Interview', 23), ('Women Dorado', 23), ('Fool Mockingbird', 23), ('Name Detective', 23), ('Kwai Homeward', 23), ('Steel Santa', 23), ('Murder Antitrust', 23), ('Yentl Idaho', 23), ('Snowman Rollercoaster', 23), ('Wind Phantom', 23), ('Scorpion Apollo', 23), ('House Dynamite', 23), ('Gentlemen Stage', 23), ('Crooked Frogmen', 23), ('Cupboard Sinners', 23), ('Salute Apollo', 23), ('Wash Heavenly', 23), ('Easy Gladiator', 23), ('Outbreak Divine', 23), ('Balloon Homeward', 23), ('Earth Vision', 23), ('Titanic Boondock', 23), ('Heavyweights Beast', 23), ('Karate Moon', 23), ('Academy Dinosaur', 23), ('Others Soup', 23), ('Flamingos Connecticut', 23), ('Aladdin Calendar', 23), ('Candles Grapes', 23), ('Affair Prejudice', 23), ('Truman Crazy', 23), ('Trouble Date', 23), ('Freddy Storm', 23), ('Jason Trap', 24), ('Caper Motions', 24), ('Ice Crossing', 24), ('Arachnophobia Rollercoaster', 24), ('Seattle Expecations', 24), ('Shootist Superfly', 24), ('Alamo Videotape', 24), ('Pacific Amistad', 24), ('Mockingbird Hollywood', 24), ('Color Philadelphia', 24), ('Roman Punk', 24), ('Orange Grapes', 24), ('Attraction Newton', 24), ('Jumping Wrath', 24), ('Strangelove Desire', 24), ('Fargo Gandhi', 24), ('Hurricane Affair', 24), ('Horn Working', 24), ('Center Dinosaur', 24), ('Slums Duck', 24), ('Sunrise League', 24), ('Drifter Commandments', 24), ('Gunfight Moon', 24), ('Sleeping Suspects', 24), ('Lola Agent', 24), ('Atlantis Cause', 24), ('Knock Warlock', 24), ('Oz Liaisons', 24), ('Celebrity Horn', 24), ('Maiden Home', 24), ('Bound Cheaper', 24), ('Wedding Apollo', 24), ('Goldfinger Sensibility', 24), ('Oscar Gold', 25), ('Trading Pinocchio', 25), ('Telemark Heartbreakers', 25), ('Shepherd Midsummer', 25), ('Mallrats United', 25), ('Clueless Bucket', 25), ('Sun Confessions', 25), ('Fish Opus', 25), ('Feud Frogmen', 25), ('Dynamite Tarzan', 25),

In [ ]:
#**9. Qué películas no se han alquilado hasta ahora.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.title, COUNT(rental.rental_id ) as num_rentals
FROM
  film
FULL JOIN
  inventory
ON
  film.film_id = inventory.film_id
FULL JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
GROUP BY
  1
HAVING COUNT(rental.rental_id)=0
ORDER BY 1
  ;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
print(result)
print(len(result))

[('Alice Fantasia', 0), ('Apollo Teen', 0), ('Argonauts Town', 0), ('Ark Ridgemont', 0), ('Arsenic Independence', 0), ('Boondock Ballroom', 0), ('Butch Panther', 0), ('Catch Amistad', 0), ('Chinatown Gladiator', 0), ('Chocolate Duck', 0), ('Commandments Express', 0), ('Crossing Divorce', 0), ('Crowds Telemark', 0), ('Crystal Breaking', 0), ('Dazed Punk', 0), ('Deliverance Mulholland', 0), ('Firehouse Vietnam', 0), ('Floats Garden', 0), ('Frankenstein Stranger', 0), ('Gladiator Westward', 0), ('Gump Date', 0), ('Hate Handicap', 0), ('Hocus Frida', 0), ('Kentuckian Giant', 0), ('Kill Brotherhood', 0), ('Muppet Mile', 0), ('Order Betrayed', 0), ('Pearl Destiny', 0), ('Perdition Fargo', 0), ('Psycho Shrunk', 0), ('Raiders Antitrust', 0), ('Rainbow Shock', 0), ('Roof Champion', 0), ('Sister Freddy', 0), ('Sky Miracle', 0), ('Suicides Silence', 0), ('Tadpole Park', 0), ('Treasure Command', 0), ('Villain Desperate', 0), ('Volume House', 0), ('Wake Jaws', 0), ('Walls Artist', 0)]
42

In [ ]:
#He probado con la opción siguiente, pero hay diferencia en una película: 'Academy Dinosaur' que no debería aparecer, y aparece porque aunque sí que tiene registros con 'rental_date', existe un registro en el que el 'rental_date' está vacío.

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
select distinct film.title
from film
FULL join
inventory
on
film.film_id = inventory.film_id
FULL Join
rental
on
rental.inventory_id = inventory.inventory_id
where rental_date is NULL
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)
print(len(result))

[('Academy Dinosaur',), ('Alice Fantasia',), ('Apollo Teen',), ('Argonauts Town',), ('Ark Ridgemont',), ('Arsenic Independence',), ('Boondock Ballroom',), ('Butch Panther',), ('Catch Amistad',), ('Chinatown Gladiator',), ('Chocolate Duck',), ('Commandments Express',), ('Crossing Divorce',), ('Crowds Telemark',), ('Crystal Breaking',), ('Dazed Punk',), ('Deliverance Mulholland',), ('Firehouse Vietnam',), ('Floats Garden',), ('Frankenstein Stranger',), ('Gladiator Westward',), ('Gump Date',), ('Hate Handicap',), ('Hocus Frida',), ('Kentuckian Giant',), ('Kill Brotherhood',), ('Muppet Mile',), ('Order Betrayed',), ('Pearl Destiny',), ('Perdition Fargo',), ('Psycho Shrunk',), ('Raiders Antitrust',), ('Rainbow Shock',), ('Roof Champion',), ('Sister Freddy',), ('Sky Miracle',), ('Suicides Silence',), ('Tadpole Park',), ('Treasure Command',), ('Villain Desperate',), ('Volume House',), ('Wake Jaws',), ('Walls Artist',)]
43

In [ ]:
10. #**Qué clientes no han alquilado ninguna película hasta ahora.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 customer.customer_id, COUNT(rental.rental_id)
FROM
  customer
LEFT JOIN
  rental
ON
  customer.customer_id = rental.customer_id
GROUP BY
  1
HAVING COUNT(rental.rental_id)=0
  ;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 customer.customer_id, COUNT(rental.rental_id)
FROM
  customer
LEFT JOIN
  rental
ON
  customer.customer_id = rental.customer_id
WHERE rental.rental_date IS NULL
GROUP BY
  1
  ;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 customer.customer_id, COUNT(rental.rental_id)
FROM
  customer
LEFT JOIN
  rental
ON
  customer.customer_id = rental.customer_id
GROUP BY
  1
ORDER BY 2 ASC ;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(318, 12),
 (281, 14),
 (61, 14),
 (110, 14),
 (136, 15),
 (248, 15),
 (492, 16),
 (164, 16),
 (464, 16),
 (398, 16),
 (465, 17),
 (555, 17),
 (48, 17),
 (223, 17),
 (315, 17),
 (140, 18),
 (205, 18),
 (194, 18),
 (255, 18),
 (271, 18),
 (344, 18),
 (542, 18),
 (97, 18),
 (353, 18),
 (70, 18),
 (218, 18),
 (483, 18),
 (95, 18),
 (124, 18),
 (395, 19),
 (524, 19),
 (378, 19),
 (525, 19),
 (458, 19),
 (370, 19),
 (195, 19),
 (599, 19),
 (586, 19),
 (117, 19),
 (478, 19),
 (548, 19),
 (310, 20),
 (509, 20),
 (320, 20),
 (272, 20),
 (203, 20),
 (212, 20),
 (191, 20),
 (402, 20),
 (250, 20),
 (449, 20),
 (549, 20),
 (162, 20),
 (567, 20),
 (428, 20),
 (355, 20),
 (568, 21),
 (552, 21),
 (489, 21),
 (545, 21),
 (496, 21),
 (401, 21),
 (556, 21),
 (174, 21),
 (429, 21),
 (222, 21),
 (238, 21),
 (226, 21),
 (301, 21),
 (420, 21),
 (505, 21),
 (358, 21),
 (33, 21),
 (152, 21),
 (412, 21),
 (501, 21),
 (118, 21),
 (159, 21),
 (399, 21),
 (413, 21),
 (94, 21),
 (165, 21),
 (88, 21),
 (17, 21),
 (247, 22),
 (189, 22),
 (18, 22),
 (79, 22),
 (477, 22),
 (321, 22),
 (476, 22),
 (68, 22),
 (440, 22),
 (55, 22),
 (578, 22),
 (367, 22),
 (544, 22),
 (67, 22),
 (554, 22),
 (4, 22),
 (47, 22),
 (325, 22),
 (65, 22),
 (443, 22),
 (598, 22),
 (514, 22),
 (539, 22),
 (81, 22),
 (543, 22),
 (394, 22),
 (22, 22),
 (430, 22),
 (488, 22),
 (252, 22),
 (224, 22),
 (523, 22),
 (480, 22),
 (169, 22),
 (143, 22),
 (192, 23),
 (106, 23),
 (530, 23),
 (185, 23),
 (76, 23),
 (392, 23),
 (432, 23),
 (335, 23),
 (311, 23),
 (313, 23),
 (184, 23),
 (183, 23),
 (493, 23),
 (365, 23),
 (466, 23),
 (62, 23),
 (233, 23),
 (437, 23),
 (180, 23),
 (352, 23),
 (328, 23),
 (134, 23),
 (246, 23),
 (345, 23),
 (216, 23),
 (291, 23),
 (453, 23),
 (217, 23),
 (177, 23),
 (93, 23),
 (37, 23),
 (341, 23),
 (379, 23),
 (364, 23),
 (415, 23),
 (431, 23),
 (350, 23),
 (9, 23),
 (85, 23),
 (519, 23),
 (409, 23),
 (521, 23),
 (249, 23),
 (583, 23),
 (547, 23),
 (427, 24),
 (375, 24),
 (564, 24),
 (99, 24),
 (127, 24),
 (534, 24),
 (571, 24),
 (11, 24),
 (541, 24),
 (153, 24),
 (475, 24),
 (175, 24),
 (490, 24),
 (123, 24),
 (553, 24),
 (527, 24),
 (455, 24),
 (288, 24),
 (130, 24),
 (227, 24),
 (8, 24),
 (100, 24),
 (351, 24),
 (585, 24),
 (19, 24),
 (34, 24),
 (43, 24),
 (243, 24),
 (73, 24),
 (540, 24),
 (511, 24),
 (258, 24),
 (382, 24),
 (104, 24),
 (557, 24),
 (101, 24),
 (326, 25),
 (98, 25),
 (24, 25),
 (10, 25),
 (201, 25),
 (582, 25),
 (83, 25),
 (155, 25),
 (324, 25),
 (305, 25),
 (433, 25),
 (308, 25),
 (536, 25),
 (508, 25),
 (232, 25),
 (572, 25),
 (193, 25),
 (270, 25),
 (63, 25),
 (597, 25),
 (528, 25),
 (463, 25),
 (384, 25),
 (359, 25),
 (229, 25),
 (150, 25),
 (456, 25),
 (60, 25),
 (417, 25),
 (69, 25),
 (414, 25),
 (330, 25),
 (537, 25),
 (507, 25),
 (343, 25),
 (264, 25),
 (419, 25),
 (460, 25),
 (562, 25),
 (590, 25),
 (435, 25),
 (235, 25),
 (156, 25),
 (517, 25),
 (546, 25),
 (188, 25),
 (199, 25),
 (531, 25),
 (369, 25),
 (41, 25),
 (587, 26),
 (121, 26),
 (240, 26),
 (171, 26),
 (298, 26),
 (261, 26),
 (208, 26),
 (357, 26),
 (385, 26),
 (111, 26),
 (219, 26),
 (285, 26),
 (231, 26),
 (512, 26),
 (487, 26),
 (142, 26),
 (516, 26),
 (182, 26),
 (225, 26),
 (294, 26),
 (304, 26),
 (450, 26),
 (170, 26),
 (510, 26),
 (44, 26),
 (202, 26),
 (82, 26),
 (551, 26),
 (3, 26),
 (518, 26),
 (387, 26),
 (389, 26),
 (278, 26),
 (312, 26),
 (570, 26),
 (377, 26),
 (423, 26),
 (593, 26),
 (411, 26),
 (425, 26),
 (495, 26),
 (234, 26),
 (474, 26),
 (109, 26),
 (422, 26),
 (327, 26),
 (215, 26),
 (486, 26),
 (31, 26),
 (445, 26),
 (105, 26),
 (303, 26),
 (149, 26),
 (580, 27),
 (160, 27),
 (40, 27),
 (498, 27),
 (396, 27),
 (471, 27),
 (421, 27),
 (407, 27),
 (74, 27),
 (151, 27),
 (116, 27),
 (200, 27),
 (282, 27),
 (286, 27),
 (59, 27),
 (426, 27),
 (579, 27),
 (190, 27),
 (491, 27),
 (228, 27),
 (58, 27),
 (561, 27),
 (333, 27),
 (45, 27),
 (2, 27),
 (13, 27),
 (292, 27),
 (36, 27),
 (594, 27),
 (220, 27),
 (133, 27),
 (96, 27),
 (139, 27),
 (280, 27),
 (577, 27),
 (581, 27),
 (591, 27),
 (383, 27),
 (331, 27),
 (206, 27),
 (434, 27),
 (6, 28),
 (187, 28),
 (57, 28),
 (266, 28),
 (400, 28),
 (596, 28),
 (166, 28),
 (145, 28),
 (559, 28),
 (276, 28),
 (589, 28),
 (457, 28),
 (90, 28),
 (558, 28),
 (290, 28),
 (284, 28),
 (317, 28),
 (126, 28),
 (374, 28),
 (12, 28),
 (332, 28),
 (92, 28),
 (500, 28),
 (461, 28),
 (283, 28),
 (14, 28),
 (497, 28),
 (441, 28),
 (132, 28),
 (322, 28),
 (262, 28),
 (504, 28),
 (376, 28),
 (338, 28),
 (77, 28),
 (515, 28),
 (574, 28),
 (213, 28),
 (221, 28),
 (16, 28),
 (49, 28),
 (565, 29),
 (52, 29),
 (253, 29),
 (592, 29),
 (179, 29),
 (263, 29),
 (32, 29),
 (163, 29),
 (573, 29),
 (113, 29),
 (349, 29),
 (588, 29),
 (302, 29),
 (575, 29),
 (482, 29),
 (173, 29),
 (447, 29),
 (363, 29),
 (39, 29),
 (54, 29),
 (316, 29),
 (265, 29),
 (481, 29),
 (397, 29),
 (268, 29),
 (287, 29),
 (538, 29),
 (146, 29),
 (25, 29),
 (448, 29),
 (386, 29),
 (529, 29),
 (467, 29),
 (485, 29),
 (337, 29),
 (563, 29),
 (53, 30),
 (23, 30),
 (584, 30),
 (404, 30),
 (424, 30),
 (131, 30),
 (408, 30),
 (108, 30),
 (72, 30),
 (115, 30),
 (256, 30),
 (154, 30),
 (269, 30),
 (339, 30),
 (135, 30),
 (275, 30),
 (336, 30),
 (42, 30),
 (161, 30),
 (20, 30),
 (319, 30),
 (472, 30),
 (307, 30),
 (444, 30),
 (107, 30),
 (347, 30),
 (436, 30),
 (299, 30),
 (71, 30),
 (87, 30),
 (80, 30),
 (499, 30),
 (334, 30),
 (484, 30),
 (356, 30),
 (391, 30),
 (418, 30),
 (595, 30),
 (296, 30),
 (112, 30),
 (560, 30),
 (289, 30),
 (56, 30),
 (388, 30),
 (323, 31),
 (260, 31),
 (214, 31),
 (479, 31),
 (210, 31),
 (27, 31),
 (186, 31),
 (416, 31),
 (513, 31),
 (393, 31),
 (446, 31),
 (494, 31),
 (157, 31),
 (309, 31),
 (251, 31),
 (300, 31),
 (103, 31),
 (279, 31),
 (361, 31),
 (340, 31),
 (293, 31),
 (78, 31),
 (158, 32),
 (89, 32),
 (122, 32),
 (442, 32),
 (254, 32),
 (503, 32),
 (1, 32),
 (342, 32),
 (277, 32),
 (167, 32),
 (346, 32),
 (245, 32),
 (209, 32),
 (569, 32),
 (452, 32),
 (259, 32),
 (532, 32),
 (306, 32),
 (329, 32),
 (535, 32),
 (406, 32),
 (405, 32),
 (28, 32),
 (550, 32),
 (128, 32),
 (520, 32),
 (362, 32),
 (35, 32),
 (242, 32),
 (120, 32),
 (125, 32),
 (244, 32),
 (15, 32),
 (141, 32),
 (470, 32),
 (237, 33),
 (114, 33),
 (314, 33),
 (451, 33),
 (64, 33),
 (102, 33),
 (297, 33),
 (533, 33),
 (86, 33),
 (462, 33),
 (454, 33),
 (7, 33),
 (230, 33),
 (390, 33),
 (522, 33),
 (84, 33),
 (438, 33),
 (172, 33),
 (51, 33),
 (207, 34),
 (473, 34),
 (26, 34),
 (576, 34),
 (241, 34),
 (168, 34),
 (66, 34),
 (181, 34),
 (129, 34),
 (360, 34),
 (239, 34),
 (46, 34),
 (119, 34),
 (566, 34),
 (502, 34),
 (147, 34),
 (30, 34),
 (138, 34),
 (38, 34),
 (211, 34),
 (372, 34),
 (91, 35),
 (204, 35),
 (368, 35),
 (381, 35),
 (373, 35),
 (273, 35),
 (274, 35),
 (506, 35),
 (403, 35),
 (21, 35),
 (50, 35),
 (196, 35),
 (371, 35),
 (354, 36),
 (380, 36),
 (439, 36),
 (29, 36),
 (348, 36),
 (267, 36),
 (257, 37),
 (176, 37),
 (366, 37),
 (198, 37),
 (5, 38),
 (459, 38),
 (295, 38),
 (410, 38),
 (468, 39),
 (178, 39),
 (137, 39),
 (469, 40),
 (197, 40),
 (75, 41),
 (236, 42),
 (144, 42),
 (526, 45),
 (148, 46)]

In [ ]:
#**11. Muestra cada película y la cantidad de veces que se alquila.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.title, COUNT(rental.rental_id) as num_rentals
FROM
  film
JOIN
  inventory
ON
  film.film_id = inventory.film_id
JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
GROUP BY
  1
ORDER BY
2 ASC;
"""


#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Mixed Doors', 4),
 ('Train Bunch', 4),
 ('Hardly Robbers', 4),
 ('Mannequin Worst', 5),
 ('Braveheart Human', 5),
 ('Bunch Minds', 5),
 ('Private Drop', 5),
 ('Traffic Hobbit', 5),
 ('Mussolini Spoilers', 5),
 ('Seven Swarm', 5),
 ('Full Flatliners', 5),
 ('Fever Empire', 5),
 ('Glory Tracy', 5),
 ('Informer Double', 5),
 ('Conspiracy Spirit', 5),
 ('Freedom Cleopatra', 5),
 ('Hunter Alter', 5),
 ('Graceland Dynamite', 6),
 ('Terminator Club', 6),
 ('Extraordinary Conquerer', 6),
 ('Oklahoma Jumanji', 6),
 ('Rushmore Mermaid', 6),
 ('Tequila Past', 6),
 ('School Jacket', 6),
 ('Happiness United', 6),
 ('Frontier Cabin', 6),
 ('Sling Luke', 6),
 ('Apocalypse Flamingos', 6),
 ('Watership Frontier', 6),
 ('Ladybugs Armageddon', 6),
 ('Bed Highball', 6),
 ('Simon North', 6),
 ('Texas Watch', 6),
 ('Bubble Grosse', 6),
 ('Jersey Sassy', 6),
 ('Haunted Antitrust', 6),
 ('Wild Apollo', 6),
 ('Duck Racer', 6),
 ('Comancheros Enemy', 6),
 ('Italian African', 6),
 ('Warlock Werewolf', 6),
 ('Desperate Trainspotting', 6),
 ('Killer Innocent', 6),
 ('Japanese Run', 6),
 ('Youth Kick', 6),
 ('Phantom Glory', 6),
 ('Cassidy Wyoming', 6),
 ('Dumbo Lust', 6),
 ('Clerks Angels', 7),
 ('Ishtar Rocketeer', 7),
 ('Doctor Grail', 7),
 ('Ace Goldfinger', 7),
 ('Control Anthem', 7),
 ('Sense Greek', 7),
 ('Treatment Jekyll', 7),
 ('Leathernecks Dwarfs', 7),
 ('Connection Microcosmos', 7),
 ('Newsies Story', 7),
 ('Clue Grail', 7),
 ('Pizza Jumanji', 7),
 ('Luke Mummy', 7),
 ('Bang Kwai', 7),
 ('Vanished Garden', 7),
 ('Early Home', 7),
 ('Panic Club', 7),
 ('President Bang', 7),
 ('Divorce Shining', 7),
 ('Duffel Apocalypse', 7),
 ('Cowboy Doom', 7),
 ('Cruelty Unforgiven', 7),
 ('Dozen Lion', 7),
 ('Stallion Sundance', 7),
 ('Magic Mallrats', 7),
 ('Squad Fish', 7),
 ('Young Language', 7),
 ('Lesson Cleopatra', 7),
 ('Hawk Chill', 7),
 ('Bulworth Commandments', 7),
 ('Eve Resurrection', 7),
 ('Mulholland Beast', 7),
 ('Fire Wolves', 7),
 ('Elf Murder', 7),
 ('Heavenly Gun', 7),
 ('Menagerie Rushmore', 7),
 ('License Weekend', 7),
 ('Vision Torque', 7),
 ('Records Zorro', 8),
 ('Park Citizen', 8),
 ('Clyde Theory', 8),
 ('Crusade Honey', 8),
 ('Gosford Donnie', 8),
 ('Maude Mod', 8),
 ('Destination Jerk', 8),
 ('Soup Wisdom', 8),
 ('Magnificent Chitty', 8),
 ('Jumanji Blade', 8),
 ('Untouchables Sunrise', 8),
 ('Tarzan Videotape', 8),
 ('World Leathernecks', 8),
 ('Lights Deer', 8),
 ('Casper Dragonfly', 8),
 ('Hoosiers Birdcage', 8),
 ('Godfather Diary', 8),
 ('Papi Necklace', 8),
 ('Saints Bride', 8),
 ('Punk Divorce', 8),
 ('Harold French', 8),
 ('Chaplin License', 8),
 ('Desire Alien', 8),
 ('Grosse Wonderful', 8),
 ('Unfaithful Kill', 8),
 ('Shining Roses', 8),
 ('Baby Hall', 8),
 ('Vertigo Northwest', 8),
 ('Pet Haunting', 8),
 ('Runner Madigan', 8),
 ('Chitty Lock', 8),
 ('Ballroom Mockingbird', 8),
 ('Soldiers Evolution', 8),
 ('Rebel Airport', 8),
 ('Sunset Racer', 8),
 ('Runaway Tenenbaums', 8),
 ('Dolls Rage', 9),
 ('Dwarfs Alter', 9),
 ('Maguire Apache', 9),
 ('Kramer Chocolate', 9),
 ('Miracle Virtual', 9),
 ('Gilbert Pelican', 9),
 ('Drop Waterfront', 9),
 ('Birdcage Casper', 9),
 ('Legally Secretary', 9),
 ('Dares Pluto', 9),
 ('Caribbean Liberty', 9),
 ('Ghostbusters Elf', 9),
 ('Victory Academy', 9),
 ('Snatchers Montezuma', 9),
 ('Casualties Encino', 9),
 ('Spartacus Cheaper', 9),
 ('Crazy Home', 9),
 ('Wisdom Worker', 9),
 ('Ali Forever', 9),
 ('Darling Breaking', 9),
 ('Hotel Happiness', 9),
 ('Nuts Ties', 9),
 ('Jungle Closer', 9),
 ('Diary Panic', 9),
 ('Vanilla Day', 9),
 ('Random Go', 9),
 ('Montezuma Command', 9),
 ('Intolerable Intentions', 9),
 ('Impact Aladdin', 9),
 ('Anything Savannah', 9),
 ('King Evolution', 9),
 ('Legend Jedi', 9),
 ('Zhivago Core', 9),
 ('Frisco Forrest', 9),
 ('Reds Pocus', 9),
 ('Monsoon Cause', 9),
 ('Holy Tadpole', 9),
 ('Speed Suit', 9),
 ('Daughter Madigan', 9),
 ('Won Dares', 9),
 ('Wonderful Drop', 9),
 ('Guys Falcon', 9),
 ('Platoon Instinct', 9),
 ('Matrix Snowman', 9),
 ('Element Freddy', 10),
 ('Oleander Clue', 10),
 ('Gone Trouble', 10),
 ('Lambs Cincinatti', 10),
 ('Frogmen Breaking', 10),
 ('Beneath Rush', 10),
 ('Spoilers Hellfighters', 10),
 ('Blood Argonauts', 10),
 ('Grail Frankenstein', 10),
 ('Madigan Dorado', 10),
 ('Doubtfire Labyrinth', 10),
 ('Antitrust Tomatoes', 10),
 ('Paths Control', 10),
 ('Amelie Hellfighters', 10),
 ('Clockwork Paradise', 10),
 ('Wars Pluto', 10),
 ('Jawbreaker Brooklyn', 10),
 ('Hollow Jeopardy', 10),
 ('Stage World', 10),
 ('Notting Speakeasy', 10),
 ('Lolita World', 10),
 ('Jeopardy Encino', 10),
 ('Smile Earring', 10),
 ('Sensibility Rear', 10),
 ('Wagon Jaws', 10),
 ('Maker Gables', 10),
 ('Right Cranes', 10),
 ('Run Pacific', 10),
 ('Fiddler Lost', 10),
 ('Life Twisted', 10),
 ('Superfly Trip', 10),
 ('Lover Truman', 10),
 ('Halloween Nuts', 10),
 ('Reservoir Adaptation', 10),
 ('Mystic Truman', 10),
 ('Elizabeth Shane', 10),
 ('Luck Opus', 10),
 ('Rollercoaster Bringing', 10),
 ('Prix Undefeated', 11),
 ('Ties Hunger', 11),
 ('Language Cowboy', 11),
 ('Iron Moon', 11),
 ('Frida Slipper', 11),
 ('Ending Crowds', 11),
 ('Bowfinger Gables', 11),
 ('Stranger Strangers', 11),
 ('Potluck Mixed', 11),
 ('Towers Hurricane', 11),
 ('Birch Antitrust', 11),
 ('Cranes Reservoir', 11),
 ('Reef Salute', 11),
 ('Gathering Calendar', 11),
 ('Thin Sagebrush', 11),
 ('Rider Caddyshack', 11),
 ('Twisted Pirates', 11),
 ('Beast Hunchback', 11),
 ('Bird Independence', 11),
 ('Magnolia Forrester', 11),
 ('Spirited Casualties', 11),
 ('Beethoven Exorcist', 11),
 ('Bugsy Song', 11),
 ('Mod Secretary', 11),
 ('North Tequila', 11),
 ('Stone Fire', 11),
 ('Trainspotting Strangers', 11),
 ('Lord Arizona', 11),
 ('Feathers Metal', 11),
 ('Autumn Crow', 11),
 ('Santa Paris', 11),
 ('Drumline Cyclone', 11),
 ('Song Hedwig', 11),
 ('Fugitive Maguire', 11),
 ('Darko Dorado', 11),
 ('Opus Ice', 11),
 ('Dragon Squad', 11),
 ('October Submarine', 11),
 ('Theory Mermaid', 11),
 ('Silverado Goldfinger', 12),
 ('Vampire Whale', 12),
 ('Crow Grease', 12),
 ('Savannah Town', 12),
 ('Meet Chocolate', 12),
 ('Smoochy Control', 12),
 ('African Egg', 12),
 ('Massage Image', 12),
 ('Minority Kiss', 12),
 ('Speakeasy Date', 12),
 ('Mighty Luck', 12),
 ('Gunfighter Mussolini', 12),
 ('Uptown Young', 12),
 ('Dangerous Uptown', 12),
 ('Tycoon Gathering', 12),
 ('Adaptation Holes', 12),
 ('Loverboy Attacks', 12),
 ('Evolution Alter', 12),
 ('Blanket Beverly', 12),
 ('War Notting', 12),
 ('Finding Anaconda', 12),
 ('Lost Bird', 12),
 ('Alabama Devil', 12),
 ('Liberty Magnificent', 12),
 ('Sorority Queen', 12),
 ('Side Ark', 12),
 ('Flight Lies', 12),
 ('Temple Attraction', 12),
 ('California Birds', 12),
 ('Mob Duffel', 12),
 ('Hedwig Alter', 12),
 ('Pittsburgh Hunchback', 12),
 ('Born Spinal', 12),
 ('Brannigan Sunrise', 12),
 ('Valentine Vanishing', 12),
 ('Window Side', 12),
 ('Chamber Italian', 13),
 ('Bright Encounters', 13),
 ('Breaking Home', 13),
 ('Tuxedo Mile', 13),
 ('Past Suicides', 13),
 ('Flash Wars', 13),
 ('Exorcist Sting', 13),
 ('Super Wyoming', 13),
 ('Cincinatti Whisperer', 13),
 ('Hollywood Anonymous', 13),
 ('Mulan Moon', 13),
 ('Hook Chariots', 13),
 ('Wyoming Storm', 13),
 ('Behavior Runaway', 13),
 ('Natural Stock', 13),
 ('Mile Mulan', 13),
 ('Bilko Anonymous', 13),
 ('Opposite Necklace', 13),
 ('Spinal Rocky', 13),
 ('Memento Zoolander', 13),
 ('Sassy Packer', 13),
 ('Spiking Element', 13),
 ('Monterey Labyrinth', 13),
 ('Chisum Behavior', 13),
 ('Darkness War', 13),
 ('Saturn Name', 13),
 ('Microcosmos Paradise', 13),
 ('Date Speed', 13),
 ('Express Lonely', 13),
 ('Lucky Flying', 13),
 ('Anonymous Human', 13),
 ('Tenenbaums Command', 13),
 ('Forever Candidate', 13),
 ('Robbery Bright', 13),
 ('Raging Airplane', 13),
 ('Purple Movie', 13),
 ('Drums Dynamite', 13),
 ('State Wasteland', 13),
 ('Usual Untouchables', 13),
 ('Jingle Sagebrush', 13),
 ('Lawrence Love', 13),
 ('Moonwalker Fool', 13),
 ('Party Knock', 13),
 ('Citizen Shrek', 13),
 ('Bedazzled Married', 13),
 ('Champion Flatliners', 13),
 ('Everyone Craft', 13),
 ('Hunger Roof', 13),
 ('Connecticut Tramp', 13),
 ('Identity Lover', 13),
 ('Daddy Pittsburgh', 13),
 ('Arabia Dogma', 13),
 ('Alley Evolution', 14),
 ('Kane Exorcist', 14),
 ('Splash Gump', 14),
 ('Blindness Gun', 14),
 ('Jaws Harry', 14),
 ('Stampede Disturbing', 14),
 ('Donnie Alley', 14),
 ('Town Ark', 14),
 ('Confessions Maguire', 14),
 ('Troopers Metal', 14),
 ('Image Princess', 14),
 ('Nemo Campus', 14),
 ('Pajama Jawbreaker', 14),
 ('Elephant Trojan', 14),
 ('Uncut Suicides', 14),
 ('Day Unfaithful', 14),
 ('Virtual Spoilers', 14),
 ('Searchers Wait', 14),
 ('Lovely Jingle', 14),
 ('Stock Glass', 14),
 ('Glass Dying', 14),
 ('Creepers Kane', 14),
 ('Peach Innocent', 14),
 ('Werewolf Lola', 14),
 ('Outlaw Hanky', 14),
 ('Mother Oleander', 14),
 ('Impossible Prejudice', 14),
 ('Analyze Hoosiers', 14),
 ('Shanghai Tycoon', 14),
 ('Hamlet Wisdom', 14),
 ('Turn Star', 14),
 ('Wrath Mile', 14),
 ('Shrunk Divine', 14),
 ('Paris Weekend', 14),
 ('Personal Ladybugs', 14),
 ('Grinch Massage', 14),
 ('Games Bowfinger', 14),
 ('Greedy Roots', 14),
 ('Gold River', 14),
 ('Deep Crusade', 14),
 ('Home Pity', 14),
 ('Dances None', 14),
 ('Shane Darkness', 14),
 ('Tomatoes Hellfighters', 14),
 ('Madre Gables', 14),
 ('Saddle Antitrust', 14),
 ('Notorious Reunion', 14),
 ('Human Graffiti', 15),
 ('Lonely Elephant', 15),
 ('Worker Tarzan', 15),
 ('Necklace Outbreak', 15),
 ('Loser Hustler', 15),
 ('Entrapment Satisfaction', 15),
 ('Cyclone Family', 15),
 ('Cabin Flash', 15),
 ('Translation Summer', 15),
 ('Ship Wonderland', 15),
 ('Nash Chocolat', 15),
 ('Anthem Luke', 15),
 ('Shrek License', 15),
 ('Dirty Ace', 15),
 ('Scissorhands Slums', 15),
 ('Boiled Dares', 15),
 ('Vietnam Smoochy', 15),
 ('Panther Reds', 15),
 ('Sons Interview', 15),
 ('Modern Dorado', 15),
 ('Sweet Brotherhood', 15),
 ('Sierra Divide', 15),
 ('Mosquito Armageddon', 15),
 ('Spirit Flintstones', 15),
 ('Odds Boogie', 15),
 ('Edge Kissing', 15),
 ('Siege Madre', 15),
 ('Hunting Musketeers', 15),
 ('Rings Heartbreakers', 15),
 ('Divine Resurrection', 15),
 ('Manchurian Curtain', 15),
 ('Lust Lock', 15),
 ('Tootsie Pilot', 15),
 ('Submarine Bed', 15),
 ('Airplane Sierra', 15),
 ('Model Fish', 15),
 ('Holes Brannigan', 15),
 ('Valley Packer', 15),
 ('Hysterical Grail', 15),
 ('Devil Desire', 15),
 ('Betrayed Rear', 15),
 ('Holiday Games', 15),
 ('Wasteland Divine', 15),
 ('Labyrinth League', 15),
 ('Charade Duffel', 15),
 ('Steers Armageddon', 15),
 ('Illusion Amelie', 15),
 ('Panky Submarine', 15),
 ('Monster Spartacus', 15),
 ('Madison Trap', 15),
 ('Circus Youth', 15),
 ('Jeepers Wedding', 16),
 ('Wizard Coldblooded', 16),
 ('Pure Runner', 16),
 ('Hall Cassidy', 16),
 ('Wanda Chamber', 16),
 ('Mummy Creatures', 16),
 ('Streak Ridgemont', 16),
 ('Dude Blindness', 16),
 ('Indian Love', 16),
 ('Willow Tracy', 16),
 ('Mermaid Insects', 16),
 ('Pluto Oleander', 16),
 ('Bonnie Holocaust', 16),
 ('Trap Guys', 16),
 ('Artist Coldblooded', 16),
 ('Conquerer Nuts', 16),
 ('Quills Bull', 16),
 ('Summer Scarface', 16),
 ('Pickup Driving', 16),
 ('Uprising Uptown', 16),
 ('Varsity Trip', 16),
 ('Graduate Lord', 16),
 ('Sagebrush Clueless', 16),
 ('Patriot Roman', 16),
 ('Attacks Hate', 16),
 ('Chicago North', 16),
 ('Caddyshack Jedi', 16),
 ('Casablanca Super', 16),
 ('Worst Banger', 16),
 ('Creatures Shakespeare', 16),
 ('West Lion', 16),
 ('Army Flintstones', 16),
 ('Coldblooded Darling', 16),
 ('Baked Cleopatra', 16),
 ('Bull Shawshank', 16),
 ('Craft Outfield', 16),
 ('Gaslight Crusade', 16),
 ('Moulin Wake', 16),
 ('Destiny Saturday', 16),
 ('Rules Human', 16),
 ('Homeward Cider', 16),
 ('Reap Unfaithful', 16),
 ('Motions Details', 16),
 ('Pilot Hoosiers', 16),
 ('Silence Kane', 16),
 ('Slipper Fidelity', 16),
 ('Lock Rear', 16),
 ('Rocky War', 16),
 ('Words Hunter', 16),
 ('Watch Tracy', 16),
 ('Pride Alamo', 16),
 ('Command Darling', 16),
 ('Daisy Menagerie', 16),
 ('Paycheck Wait', 16),
 ('Lawless Vision', 17),
 ('Sugar Wonka', 17),
 ('Intentions Empire', 17),
 ('Flintstones Happiness', 17),
 ('Roots Remember', 17),
 ('Louisiana Harry', 17),
 ('Conversation Downhill', 17),
 ('Musketeers Wait', 17),
 ('Factory Dragon', 17),
 ('Jericho Mulan', 17),
 ('Perfect Groove', 17),
 ('Teen Apollo', 17),
 ('Potter Connecticut', 17),
 ('Newton Labyrinth', 17),
 ('Idaho Love', 17),
 ('Majestic Floats', 17),
 ('Poseidon Forever', 17),
 ('Breakfast Goldfinger', 17),
 ('Taxi Kick', 17),
 ('Satisfaction Confidential', 17),
 ('Jekyll Frogmen', 17),
 ('Holocaust Highball', 17),
 ('Virgin Daisy', 17),
 ('Mask Peach', 17),
 ('Dying Maker', 17),
 ('League Hellfighters', 17),
 ('Hanover Galaxy', 17),
 ('Beach Heartbreakers', 17),
 ('Lady Stage', 17),
 ('Waterfront Deliverance', 17),
 ('United Pilot', 17),
 ('Gandhi Kwai', 17),
 ('Bikini Borrowers', 17),
 ('Rear Trading', 17),
 ('Strangers Graffiti', 17),
 ('Egypt Tenenbaums', 17),
 ('Joon Northwest', 17),
 ('Freaky Pocus', 17),
 ('Noon Papi', 17),
 ('Midnight Westward', 17),
 ('Rock Instinct', 17),
 ('Zoolander Fiction', 17),
 ('French Holiday', 17),
 ('Comforts Rush', 17),
 ('Confused Candles', 17),
 ('Orient Closer', 17),
 ('Greek Everyone', 17),
 ('Slacker Liaisons', 17),
 ('Ferris Mother', 17),
 ('Airport Pollock', 18),
 ('Dragonfly Strangers', 18),
 ('Sweden Shining', 18),
 ('Mission Zoolander', 18),
 ('Alone Trip', 18),
 ('Candidate Perdition', 18),
 ('Whale Bikini', 18),
 ('Expecations Natural', 18),
 ('Enough Raging', 18),
 ('Birds Perdition', 18),
 ('Hope Tootsie', 18),
 ('Lion Uncut', 18),
 ('Barefoot Manchurian', 18),
 ('Smoking Barbarella', 18),
 ('Insects Stone', 18),
 ('Galaxy Sweethearts', 18),
 ('Core Suit', 18),
 ('Groundhog Uncut', 18),
 ('Jacket Frisco', 18),
 ('Cleopatra Devil', 18),
 ('Secretary Rouge', 18),
 ('Instinct Airport', 18),
 ('Pollock Deliverance', 18),
 ('Unforgiven Zoolander', 18),
 ('Scarface Bang', 18),
 ('Wonka Sea', 18),
 ('Weekend Personal', 18),
 ('Vanishing Rocky', 18),
 ('Inch Jet', 18),
 ('Driver Annie', 18),
 ('Rouge Squad', 18),
 ('Polish Brooklyn', 18),
 ('Forrest Sons', 18),
 ('Carol Texas', 18),
 ('Boulevard Mob', 18),
 ('Jade Bunch', 18),
 ('Paradise Sabrina', 18),
 ('Heaven Freedom', 18),
 ('Dawn Pond', 18),
 ('Racer Egg', 18),
 ('Groove Fiction', 18),
 ('Remember Diary', 18),
 ('Darn Forrester', 18),
 ('Encino Elf', 19),
 ('Gorgeous Bingo', 19),
 ('Hanging Deep', 19),
 ('Bill Others', 19),
 ('Requiem Tycoon', 19),
 ('Campus Remember', 19),
 ('Fantasia Park', 19),
 ('Cider Desire', 19),
 ('Pond Seattle', 19),
 ('Road Roxanne', 19),
 ('Shawshank Bubble', 19),
 ('Bride Intrigue', 19),
 ('Gables Metropolis', 19),
 ('Independence Hotel', 19),
 ('Desert Poseidon', 19),
 ('Mine Titans', 19),
 ('Voice Peach', 19),
 ('Mars Roman', 19),
 ('Patient Sister', 19),
 ('Fury Murder', 19),
 ('Roxanne Rebel', 19),
 ('Encounters Curtain', 19),
 ('Hours Rage', 19),
 ('Fiction Christmas', 19),
 ('Something Duck', 19),
 ('Trojan Tomorrow', 19),
 ('Jedi Beneath', 19),
 ('Thief Pelican', 19),
 ('Canyon Stock', 19),
 ('Igby Maker', 19),
 ('Rage Games', 19),
 ('National Story', 19),
 ('Clones Pinocchio', 19),
 ('Neighbors Charade', 19),
 ('Sundance Invasion', 19),
 ('Disciple Mother', 19),
 ('Club Graffiti', 19),
 ('Honey Ties', 19),
 ('Music Boondock', 19),
 ('Details Packer', 19),
 ('Novocaine Flight', 19),
 ('Earring Instinct', 19),
 ('Backlash Undefeated', 19),
 ('Doors President', 19),
 ('Eyes Driving', 19),
 ('Heartbreakers Bright', 20),
 ('Harper Dying', 20),
 ('Masked Bubble', 20),
 ('Intrigue Worst', 20),
 ('Million Ace', 20),
 ('Room Roman', 20),
 ('Money Harold', 20),
 ('Outfield Massacre', 20),
 ('Pinocchio Simon', 20),
 ('Minds Truman', 20),
 ('Sleepless Monsoon', 20),
 ('Garden Island', 20),
 ('Kick Savannah', 20),
 ('Tramp Others', 20),
 ('Cheaper Clyde', 20),
 ('Northwest Polish', 20),
 ('Chocolat Harry', 20),
 ('Love Suicides', 20),
 ('Bringing Hysterical', 20),
 ('Secrets Paradise', 20),
 ('Prejudice Oleander', 20),
 ('Chasing Fight', 20),
 ('Peak Forever', 20),
 ('Straight Hours', 20),
 ('Stepmom Dream', 20),
 ('Hellfighters Sierra', 20),
 ('Reunion Witches', 20),
 ('Reign Gentlemen', 20),
 ('Jet Neighbors', 20),
 ('Kissing Dolls', 20),
 ('Flying Hook', 20),
 ('Jerk Paycheck', 20),
 ('Insider Arizona', 20),
 ('Dinosaur Secretary', 20),
 ('Go Purple', 20),
 ('Spice Sorority', 20),
 ('Interview Liaisons', 20),
 ('Dalmations Sweden', 20),
 ('Redemption Comforts', 20),
 ('Hunchback Impossible', 20),
 ('River Outlaw', 20),
 ('Wrong Behavior', 20),
 ('Quest Mussolini', 20),
 ('Splendor Patton', 21),
 ('Sabrina Midnight', 21),
 ('Fidelity Devil', 21),
 ('Amistad Midsummer', 21),
 ('Star Operation', 21),
 ('Badman Dawn', 21),
 ('Unbreakable Karate', 21),
 ('Wolves Desire', 21),
 ('Blues Instinct', 21),
 ('Pianist Outfield', 21),
 ('Lebowski Soldiers', 21),
 ('Highball Potter', 21),
 ('Chariots Conspiracy', 21),
 ('Pirates Roxanne', 21),
 ('Coast Rainbow', 21),
 ('Mourning Purple', 21),
 ('Amadeus Holy', 21),
 ('Crossroads Casualties', 21),
 ('Sting Personal', 21),
 ('Vacation Boondock', 21),
 ('Moonshine Cabin', 21),
 ('Sleuth Orient', 21),
 ('Divide Monster', 21),
 ('Chainsaw Uptown', 21),
 ('Agent Truman', 21),
 ('Open African', 21),
 ('Armageddon Lost', 21),
 ('Secret Groundhog', 21),
 ('Calendar Gunfight', 21),
 ('Deceiver Betrayed', 21),
 ('Christmas Moonshine', 21),
 ('Beverly Outlaw', 21),
 ('Doom Dancing', 21),
 ('Suit Walls', 21),
 ('Arizona Bang', 21),
 ('Egg Igby', 21),
 ('Cause Date', 21),
 ('Brooklyn Desert', 21),
 ('Wait Cider', 21),
 ('Resurrection Silverado', 21),
 ('Empire Malkovich', 21),
 ('Anaconda Confessions', 21),
 ('Undefeated Dalmations', 21),
 ('Fireball Philadelphia', 21),
 ('Sleepy Japanese', 21),
 ('Basic Easy', 21),
 ('Driving Polish', 21),
 ('Dracula Crystal', 21),
 ('Excitement Eve', 21),
 ('Berets Agent', 21),
 ('Grease Youth', 21),
 ('Ghost Groundhog', 21),
 ('Homicide Peach', 22),
 ('Maltese Hope', 22),
 ('South Wait', 22),
 ('Shakespeare Saddle', 22),
 ('Dream Pickup', 22),
 ('Midsummer Groundhog', 22),
 ('Angels Life', 22),
 ('American Circus', 22),
 ('Borrowers Bedazzled', 22),
 ('Chill Luck', 22),
 ('Packer Madigan', 22),
 ('Queen Luke', 22),
 ('Hustler Party', 22),
 ('Bear Graceland', 22),
 ('Tourist Pelican', 22),
 ('Flatliners Killer', 22),
 ('Sea Virgin', 22),
 ('Beauty Grease', 22),
 ('Banger Pinocchio', 22),
 ('Eagles Panky', 22),
 ('High Encino', 22),
 ('Head Stranger', 22),
 ('Kiss Glory', 22),
 ('Blade Polish', 22),
 ('Fight Jawbreaker', 22),
 ('Chicken Hellfighters', 22),
 ('Sinners Atlantis', 22),
 ('Snatch Slipper', 22),
 ('Volcano Texas', 22),
 ('Alter Victory', 22),
 ('Falcon Volume', 22),
 ('Wonderland Christmas', 22),
 ('Liaisons Sweet', 22),
 ('Congeniality Quest', 22),
 ('Grapes Fury', 22),
 ('Whisperer Giant', 22),
 ('Haunting Pianist', 22),
 ('Annie Identity', 22),
 ('Alien Center', 22),
 ('Strictly Scarface', 23),
 ('Philadelphia Wife', 23),
 ('Carrie Bunch', 23),
 ('Patton Interview', 23),
 ('Women Dorado', 23),
 ('Fool Mockingbird', 23),
 ('Name Detective', 23),
 ('Kwai Homeward', 23),
 ('Steel Santa', 23),
 ('Murder Antitrust', 23),
 ('Yentl Idaho', 23),
 ('Snowman Rollercoaster', 23),
 ('Wind Phantom', 23),
 ('Scorpion Apollo', 23),
 ('House Dynamite', 23),
 ('Gentlemen Stage', 23),
 ('Crooked Frogmen', 23),
 ('Cupboard Sinners', 23),
 ('Salute Apollo', 23),
 ('Wash Heavenly', 23),
 ('Easy Gladiator', 23),
 ('Outbreak Divine', 23),
 ('Balloon Homeward', 23),
 ('Earth Vision', 23),
 ('Titanic Boondock', 23),
 ('Heavyweights Beast', 23),
 ('Karate Moon', 23),
 ('Academy Dinosaur', 23),
 ('Others Soup', 23),
 ('Flamingos Connecticut', 23),
 ('Aladdin Calendar', 23),
 ('Candles Grapes', 23),
 ('Affair Prejudice', 23),
 ('Truman Crazy', 23),
 ('Trouble Date', 23),
 ('Freddy Storm', 23),
 ('Jason Trap', 24),
 ('Caper Motions', 24),
 ('Ice Crossing', 24),
 ('Arachnophobia Rollercoaster', 24),
 ('Seattle Expecations', 24),
 ('Shootist Superfly', 24),
 ('Alamo Videotape', 24),
 ('Pacific Amistad', 24),
 ('Mockingbird Hollywood', 24),
 ('Color Philadelphia', 24),

In [ ]:
#**12. Muestra la cantidad de películas en las que actuó cada actor.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 actor.actor_id, actor.first_name, actor.last_name, COUNT(film_actor.film_id)
FROM
  actor
LEFT JOIN
  film_actor
ON
  film_actor.actor_id = actor.actor_id
GROUP BY
  1
ORDER BY 4 DESC;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(107, 'Gina', 'Degeneres', 42),
 (102, 'Walter', 'Torn', 41),
 (198, 'Mary', 'Keitel', 40),
 (181, 'Matthew', 'Carrey', 39),
 (23, 'Sandra', 'Kilmer', 37),
 (81, 'Scarlett', 'Damon', 36),
 (158, 'Vivien', 'Basinger', 35),
 (60, 'Henry', 'Berry', 35),
 (144, 'Angela', 'Witherspoon', 35),
 (37, 'Val', 'Bolger', 35),
 (106, 'Groucho', 'Dunst', 35),
 (13, 'Uma', 'Wood', 35),
 (150, 'Jayne', 'Nolte', 34),
 (105, 'Sidney', 'Crowe', 34),
 (65, 'Angela', 'Hudson', 34),
 (92, 'Kirsten', 'Akroyd', 34),
 (108, 'Warren', 'Nolte', 34),
 (27, 'Julia', 'Mcqueen', 33),
 (117, 'Renee', 'Tracy', 33),
 (94, 'Kenneth', 'Torn', 33),
 (139, 'Ewan', 'Gooding', 33),
 (146, 'Albert', 'Johansson', 33),
 (111, 'Cameron', 'Zellweger', 33),
 (101, 'Susan', 'Davis', 33),
 (90, 'Sean', 'Guiness', 33),
 (83, 'Ben', 'Willis', 33),
 (197, 'Reese', 'West', 33),
 (127, 'Kevin', 'Garland', 33),
 (187, 'Renee', 'Ball', 33),
 (26, 'Rip', 'Crawford', 33),
 (157, 'Greta', 'Malden', 32),
 (17, 'Helen', 'Voight', 32),
 (136, 'Ed', 'Mansfield', 32),
 (119, 'Warren', 'Jackman', 32),
 (45, 'Reese', 'Kilmer', 32),
 (140, 'Whoopi', 'Hurt', 32),
 (50, 'Natalie', 'Hopkins', 32),
 (161, 'Harvey', 'Hope', 32),
 (123, 'Julianne', 'Dench', 32),
 (58, 'Christian', 'Akroyd', 32),
 (142, 'Jada', 'Ryder', 31),
 (84, 'James', 'Pitt', 31),
 (149, 'Russell', 'Temple', 31),
 (82, 'Woody', 'Jolie', 31),
 (125, 'Albert', 'Nolte', 31),
 (147, 'Fay', 'Winslet', 31),
 (85, 'Minnie', 'Zellweger', 31),
 (95, 'Daryl', 'Wahlberg', 31),
 (28, 'Woody', 'Hoffman', 31),
 (104, 'Penelope', 'Cronyn', 31),
 (168, 'Will', 'Wilson', 31),
 (66, 'Mary', 'Tandy', 31),
 (155, 'Ian', 'Tandy', 31),
 (12, 'Karl', 'Berry', 31),
 (76, 'Angelina', 'Astaire', 31),
 (143, 'River', 'Dean', 31),
 (57, 'Jude', 'Cruise', 30),
 (44, 'Nick', 'Stallone', 30),
 (103, 'Matthew', 'Leigh', 30),
 (20, 'Lucille', 'Tracy', 30),
 (191, 'Gregory', 'Gooding', 30),
 (14, 'Vivien', 'Bergen', 30),
 (133, 'Richard', 'Penn', 30),
 (128, 'Cate', 'Mcqueen', 30),
 (53, 'Mena', 'Temple', 30),
 (7, 'Grace', 'Mostel', 30),
 (196, 'Bela', 'Walken', 30),
 (68, 'Rip', 'Winslet', 30),
 (129, 'Daryl', 'Crawford', 30),
 (188, 'Rock', 'Dukakis', 30),
 (64, 'Ray', 'Johansson', 30),
 (185, 'Michael', 'Bolger', 30),
 (192, 'John', 'Suvari', 29),
 (176, 'Jon', 'Chase', 29),
 (36, 'Burt', 'Dukakis', 29),
 (169, 'Kenneth', 'Hoffman', 29),
 (40, 'Johnny', 'Cage', 29),
 (184, 'Humphrey', 'Garland', 29),
 (5, 'Johnny', 'Lollobrigida', 29),
 (179, 'Ed', 'Guiness', 29),
 (29, 'Alec', 'Wayne', 29),
 (41, 'Jodie', 'Degeneres', 29),
 (62, 'Jayne', 'Neeson', 29),
 (56, 'Dan', 'Harris', 28),
 (39, 'Goldie', 'Brody', 28),
 (80, 'Ralph', 'Cruz', 28),
 (74, 'Milla', 'Keitel', 28),
 (171, 'Olympia', 'Pfeiffer', 28),
 (79, 'Mae', 'Hoffman', 28),
 (154, 'Meryl', 'Gibson', 28),
 (141, 'Cate', 'Harris', 28),
 (115, 'Harrison', 'Bale', 28),
 (15, 'Cuba', 'Olivier', 28),
 (145, 'Kim', 'Allen', 28),
 (97, 'Meg', 'Hawke', 27),
 (16, 'Fred', 'Costner', 27),
 (49, 'Anne', 'Cronyn', 27),
 (21, 'Kirsten', 'Paltrow', 27),
 (177, 'Gene', 'Mckellen', 27),
 (59, 'Dustin', 'Tautou', 27),
 (137, 'Morgan', 'Williams', 27),
 (195, 'Jayne', 'Silverstone', 27),
 (42, 'Tom', 'Miranda', 27),
 (98, 'Chris', 'Bridges', 27),
 (173, 'Alan', 'Dreyfuss', 27),
 (113, 'Morgan', 'Hopkins', 27),
 (86, 'Greg', 'Chaplin', 27),
 (130, 'Greta', 'Keitel', 27),
 (120, 'Penelope', 'Monroe', 27),
 (190, 'Audrey', 'Bailey', 27),
 (175, 'William', 'Hackman', 27),
 (151, 'Geoffrey', 'Heston', 26),
 (43, 'Kirk', 'Jovovich', 26),
 (48, 'Frances', 'Day-Lewis', 26),
 (124, 'Scarlett', 'Bening', 26),
 (72, 'Sean', 'Williams', 26),
 (22, 'Elvis', 'Marx', 26),
 (165, 'Al', 'Garland', 26),
 (167, 'Laurence', 'Bullock', 26),
 (99, 'Jim', 'Mostel', 26),
 (52, 'Carmen', 'Hunt', 26),
 (164, 'Humphrey', 'Willis', 26),
 (78, 'Groucho', 'Sinatra', 26),
 (159, 'Laura', 'Brody', 26),
 (73, 'Gary', 'Penn', 26),
 (172, 'Groucho', 'Williams', 25),
 (122, 'Salma', 'Nolte', 25),
 (38, 'Tom', 'Mckellen', 25),
 (51, 'Gary', 'Phoenix', 25),
 (9, 'Joe', 'Swank', 25),
 (131, 'Jane', 'Jackman', 25),
 (11, 'Zero', 'Cage', 25),
 (118, 'Cuba', 'Allen', 25),
 (114, 'Morgan', 'Mcdormand', 25),
 (61, 'Christian', 'Neeson', 25),
 (162, 'Oprah', 'Kilmer', 25),
 (2, 'Nick', 'Wahlberg', 25),
 (180, 'Jeff', 'Silverstone', 25),
 (121, 'Liza', 'Bergman', 25),
 (112, 'Russell', 'Bacall', 25),
 (34, 'Audrey', 'Olivier', 25),
 (19, 'Bob', 'Fawcett', 25),
 (93, 'Ellen', 'Presley', 25),
 (54, 'Penelope', 'Pinkett', 25),
 (77, 'Cary', 'Mcconaughey', 24),
 (189, 'Cuba', 'Birch', 24),
 (24, 'Cameron', 'Streep', 24),
 (174, 'Michael', 'Bening', 24),
 (33, 'Milla', 'Peck', 24),
 (182, 'Debbie', 'Akroyd', 24),
 (170, 'Mena', 'Hopper', 24),
 (47, 'Julia', 'Barrymore', 24),
 (89, 'Charlize', 'Dench', 24),
 (138, 'Lucille', 'Dee', 24),
 (116, 'Dan', 'Streep', 24),
 (46, 'Parker', 'Goldberg', 24),
 (100, 'Spencer', 'Depp', 24),
 (75, 'Burt', 'Posey', 24),
 (178, 'Lisa', 'Monroe', 23),
 (67, 'Jessica', 'Bailey', 23),
 (96, 'Gene', 'Willis', 23),
 (126, 'Frances', 'Tomei', 23),
 (152, 'Ben', 'Harris', 23),
 (70, 'Michelle', 'Mcconaughey', 23),
 (32, 'Tim', 'Hackman', 23),
 (193, 'Burt', 'Temple', 23),
 (18, 'Dan', 'Torn', 22),
 (3, 'Ed', 'Chase', 22),
 (156, 'Fay', 'Wood', 22),
 (4, 'Jennifer', 'Davis', 22),
 (166, 'Nick', 'Degeneres', 22),
 (194, 'Meryl', 'Allen', 22),
 (132, 'Adam', 'Hopper', 22),
 (10, 'Christian', 'Gable', 22),
 (109, 'Sylvester', 'Dern', 22),
 (134, 'Gene', 'Hopkins', 22),
 (163, 'Christopher', 'West', 21),
 (25, 'Kevin', 'Bloom', 21),
 (110, 'Susan', 'Davis', 21),
 (87, 'Spencer', 'Peck', 21),
 (69, 'Kenneth', 'Paltrow', 21),
 (8, 'Matthew', 'Johansson', 20),
 (135, 'Rita', 'Reynolds', 20),
 (88, 'Kenneth', 'Pesci', 20),
 (160, 'Chris', 'Depp', 20),
 (200, 'Thora', 'Temple', 20),
 (6, 'Bette', 'Nicholson', 20),
 (153, 'Minnie', 'Kilmer', 20),
 (55, 'Fay', 'Kilmer', 20),
 (91, 'Christopher', 'Berry', 20),
 (30, 'Sandra', 'Peck', 19),
 (1, 'Penelope', 'Guiness', 19),
 (63, 'Cameron', 'Wray', 19),
 (183, 'Russell', 'Close', 19),
 (31, 'Sissy', 'Sobieski', 18),
 (71, 'Adam', 'Grant', 18),
 (186, 'Julia', 'Zellweger', 16),
 (35, 'Judy', 'Dean', 15),
 (199, 'Julia', 'Fawcett', 15),
 (148, 'Emily', 'Dee', 14)]

In [ ]:
#**13. Muestre los nombres de los actores que actuaron en más de 20 películas.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 actor.actor_id, actor.first_name, actor.last_name, COUNT(film_actor.film_id)
FROM
  actor
LEFT JOIN
  film_actor
ON
  film_actor.actor_id = actor.actor_id
GROUP BY
  1
HAVING COUNT(film_actor.film_id)>20
ORDER BY
  4 DESC;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(107, 'Gina', 'Degeneres', 42),
 (102, 'Walter', 'Torn', 41),
 (198, 'Mary', 'Keitel', 40),
 (181, 'Matthew', 'Carrey', 39),
 (23, 'Sandra', 'Kilmer', 37),
 (81, 'Scarlett', 'Damon', 36),
 (60, 'Henry', 'Berry', 35),
 (37, 'Val', 'Bolger', 35),
 (144, 'Angela', 'Witherspoon', 35),
 (106, 'Groucho', 'Dunst', 35),
 (158, 'Vivien', 'Basinger', 35),
 (13, 'Uma', 'Wood', 35),
 (150, 'Jayne', 'Nolte', 34),
 (108, 'Warren', 'Nolte', 34),
 (105, 'Sidney', 'Crowe', 34),
 (92, 'Kirsten', 'Akroyd', 34),
 (65, 'Angela', 'Hudson', 34),
 (146, 'Albert', 'Johansson', 33),
 (90, 'Sean', 'Guiness', 33),
 (83, 'Ben', 'Willis', 33),
 (101, 'Susan', 'Davis', 33),
 (94, 'Kenneth', 'Torn', 33),
 (139, 'Ewan', 'Gooding', 33),
 (197, 'Reese', 'West', 33),
 (127, 'Kevin', 'Garland', 33),
 (117, 'Renee', 'Tracy', 33),
 (111, 'Cameron', 'Zellweger', 33),
 (26, 'Rip', 'Crawford', 33),
 (187, 'Renee', 'Ball', 33),
 (27, 'Julia', 'Mcqueen', 33),
 (136, 'Ed', 'Mansfield', 32),
 (17, 'Helen', 'Voight', 32),
 (157, 'Greta', 'Malden', 32),
 (123, 'Julianne', 'Dench', 32),
 (161, 'Harvey', 'Hope', 32),
 (119, 'Warren', 'Jackman', 32),
 (45, 'Reese', 'Kilmer', 32),
 (50, 'Natalie', 'Hopkins', 32),
 (58, 'Christian', 'Akroyd', 32),
 (140, 'Whoopi', 'Hurt', 32),
 (168, 'Will', 'Wilson', 31),
 (155, 'Ian', 'Tandy', 31),
 (143, 'River', 'Dean', 31),
 (28, 'Woody', 'Hoffman', 31),
 (76, 'Angelina', 'Astaire', 31),
 (66, 'Mary', 'Tandy', 31),
 (85, 'Minnie', 'Zellweger', 31),
 (82, 'Woody', 'Jolie', 31),
 (142, 'Jada', 'Ryder', 31),
 (125, 'Albert', 'Nolte', 31),
 (12, 'Karl', 'Berry', 31),
 (104, 'Penelope', 'Cronyn', 31),
 (95, 'Daryl', 'Wahlberg', 31),
 (149, 'Russell', 'Temple', 31),
 (147, 'Fay', 'Winslet', 31),
 (84, 'James', 'Pitt', 31),
 (103, 'Matthew', 'Leigh', 30),
 (128, 'Cate', 'Mcqueen', 30),
 (191, 'Gregory', 'Gooding', 30),
 (188, 'Rock', 'Dukakis', 30),
 (133, 'Richard', 'Penn', 30),
 (196, 'Bela', 'Walken', 30),
 (68, 'Rip', 'Winslet', 30),
 (57, 'Jude', 'Cruise', 30),
 (185, 'Michael', 'Bolger', 30),
 (14, 'Vivien', 'Bergen', 30),
 (64, 'Ray', 'Johansson', 30),
 (129, 'Daryl', 'Crawford', 30),
 (20, 'Lucille', 'Tracy', 30),
 (7, 'Grace', 'Mostel', 30),
 (53, 'Mena', 'Temple', 30),
 (44, 'Nick', 'Stallone', 30),
 (62, 'Jayne', 'Neeson', 29),
 (41, 'Jodie', 'Degeneres', 29),
 (179, 'Ed', 'Guiness', 29),
 (5, 'Johnny', 'Lollobrigida', 29),
 (40, 'Johnny', 'Cage', 29),
 (29, 'Alec', 'Wayne', 29),
 (192, 'John', 'Suvari', 29),
 (184, 'Humphrey', 'Garland', 29),
 (169, 'Kenneth', 'Hoffman', 29),
 (176, 'Jon', 'Chase', 29),
 (36, 'Burt', 'Dukakis', 29),
 (141, 'Cate', 'Harris', 28),
 (80, 'Ralph', 'Cruz', 28),
 (115, 'Harrison', 'Bale', 28),
 (15, 'Cuba', 'Olivier', 28),
 (79, 'Mae', 'Hoffman', 28),
 (171, 'Olympia', 'Pfeiffer', 28),
 (56, 'Dan', 'Harris', 28),
 (74, 'Milla', 'Keitel', 28),
 (39, 'Goldie', 'Brody', 28),
 (154, 'Meryl', 'Gibson', 28),
 (145, 'Kim', 'Allen', 28),
 (113, 'Morgan', 'Hopkins', 27),
 (16, 'Fred', 'Costner', 27),
 (42, 'Tom', 'Miranda', 27),
 (98, 'Chris', 'Bridges', 27),
 (173, 'Alan', 'Dreyfuss', 27),
 (130, 'Greta', 'Keitel', 27),
 (21, 'Kirsten', 'Paltrow', 27),
 (137, 'Morgan', 'Williams', 27),
 (175, 'William', 'Hackman', 27),
 (190, 'Audrey', 'Bailey', 27),
 (97, 'Meg', 'Hawke', 27),
 (120, 'Penelope', 'Monroe', 27),
 (177, 'Gene', 'Mckellen', 27),
 (49, 'Anne', 'Cronyn', 27),
 (195, 'Jayne', 'Silverstone', 27),
 (86, 'Greg', 'Chaplin', 27),
 (59, 'Dustin', 'Tautou', 27),
 (159, 'Laura', 'Brody', 26),
 (22, 'Elvis', 'Marx', 26),
 (43, 'Kirk', 'Jovovich', 26),
 (151, 'Geoffrey', 'Heston', 26),
 (124, 'Scarlett', 'Bening', 26),
 (164, 'Humphrey', 'Willis', 26),
 (48, 'Frances', 'Day-Lewis', 26),
 (99, 'Jim', 'Mostel', 26),
 (167, 'Laurence', 'Bullock', 26),
 (73, 'Gary', 'Penn', 26),
 (165, 'Al', 'Garland', 26),
 (78, 'Groucho', 'Sinatra', 26),
 (52, 'Carmen', 'Hunt', 26),
 (72, 'Sean', 'Williams', 26),
 (131, 'Jane', 'Jackman', 25),
 (54, 'Penelope', 'Pinkett', 25),
 (51, 'Gary', 'Phoenix', 25),
 (93, 'Ellen', 'Presley', 25),
 (172, 'Groucho', 'Williams', 25),
 (19, 'Bob', 'Fawcett', 25),
 (61, 'Christian', 'Neeson', 25),
 (9, 'Joe', 'Swank', 25),
 (118, 'Cuba', 'Allen', 25),
 (2, 'Nick', 'Wahlberg', 25),
 (121, 'Liza', 'Bergman', 25),
 (11, 'Zero', 'Cage', 25),
 (38, 'Tom', 'Mckellen', 25),
 (112, 'Russell', 'Bacall', 25),
 (114, 'Morgan', 'Mcdormand', 25),
 (180, 'Jeff', 'Silverstone', 25),
 (122, 'Salma', 'Nolte', 25),
 (162, 'Oprah', 'Kilmer', 25),
 (34, 'Audrey', 'Olivier', 25),
 (75, 'Burt', 'Posey', 24),
 (189, 'Cuba', 'Birch', 24),
 (116, 'Dan', 'Streep', 24),
 (77, 'Cary', 'Mcconaughey', 24),
 (89, 'Charlize', 'Dench', 24),
 (24, 'Cameron', 'Streep', 24),
 (47, 'Julia', 'Barrymore', 24),
 (170, 'Mena', 'Hopper', 24),
 (182, 'Debbie', 'Akroyd', 24),
 (33, 'Milla', 'Peck', 24),
 (138, 'Lucille', 'Dee', 24),
 (174, 'Michael', 'Bening', 24),
 (46, 'Parker', 'Goldberg', 24),
 (100, 'Spencer', 'Depp', 24),
 (126, 'Frances', 'Tomei', 23),
 (32, 'Tim', 'Hackman', 23),
 (178, 'Lisa', 'Monroe', 23),
 (70, 'Michelle', 'Mcconaughey', 23),
 (96, 'Gene', 'Willis', 23),
 (193, 'Burt', 'Temple', 23),
 (67, 'Jessica', 'Bailey', 23),
 (152, 'Ben', 'Harris', 23),
 (156, 'Fay', 'Wood', 22),
 (134, 'Gene', 'Hopkins', 22),
 (3, 'Ed', 'Chase', 22),
 (166, 'Nick', 'Degeneres', 22),
 (132, 'Adam', 'Hopper', 22),
 (194, 'Meryl', 'Allen', 22),
 (109, 'Sylvester', 'Dern', 22),
 (18, 'Dan', 'Torn', 22),
 (10, 'Christian', 'Gable', 22),
 (4, 'Jennifer', 'Davis', 22),
 (163, 'Christopher', 'West', 21),
 (110, 'Susan', 'Davis', 21),
 (25, 'Kevin', 'Bloom', 21),
 (69, 'Kenneth', 'Paltrow', 21),
 (87, 'Spencer', 'Peck', 21)]

In [ ]:
#**14. ¿Cuántos actores tienen 8 letras solo en sus nombres?**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 first_name, last_name
FROM
  actor
WHERE
  length(first_name)=8;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Penelope', 'Guiness'),
 ('Jennifer', 'Davis'),
 ('Penelope', 'Pinkett'),
 ('Michelle', 'Mcconaughey'),
 ('Angelina', 'Astaire'),
 ('Scarlett', 'Damon'),
 ('Charlize', 'Dench'),
 ('Penelope', 'Cronyn'),
 ('Harrison', 'Bale'),
 ('Penelope', 'Monroe'),
 ('Julianne', 'Dench'),
 ('Scarlett', 'Bening'),
 ('Geoffrey', 'Heston'),
 ('Humphrey', 'Willis'),
 ('Laurence', 'Bullock'),
 ('Humphrey', 'Garland')]

In [ ]:
#**15**.**Para todas las películas clasificadas como "PG", muéstrame la película y la cantidad de veces que se alquiló.**
#Escribir una subconsulta para seleccionar todos los film_ids que se han alquilado hasta ahora. Para eso, se necesita unir tablas de alquiler e inventario en la columna común Inventory_id.

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.title, COUNT(rental.rental_id) as num_rentals
FROM
  film
FULL JOIN
  inventory
ON
  film.film_id = inventory.film_id
FULL JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
WHERE
  rating = 'PG'
GROUP BY
  1
ORDER BY
2 ASC;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[('Rainbow Shock', 0),
 ('Muppet Mile', 0),
 ('Walls Artist', 0),
 ('Chinatown Gladiator', 0),
 ('Arsenic Independence', 0),
 ('Hate Handicap', 0),
 ('Gladiator Westward', 0),
 ('Sky Miracle', 0),
 ('Kentuckian Giant', 0),
 ('Volume House', 0),
 ('Tadpole Park', 0),
 ('Private Drop', 5),
 ('Full Flatliners', 5),
 ('Tequila Past', 6),
 ('Jersey Sassy', 6),
 ('Oklahoma Jumanji', 6),
 ('Cowboy Doom', 7),
 ('Magic Mallrats', 7),
 ('Treatment Jekyll', 7),
 ('Mulholland Beast', 7),
 ('President Bang', 7),
 ('Squad Fish', 7),
 ('Pet Haunting', 8),
 ('Records Zorro', 8),
 ('Papi Necklace', 8),
 ('Punk Divorce', 8),
 ('Ali Forever', 9),
 ('Frisco Forrest', 9),
 ('Legally Secretary', 9),
 ('Legend Jedi', 9),
 ('Monsoon Cause', 9),
 ('Won Dares', 9),
 ('Crazy Home', 9),
 ('Oleander Clue', 10),
 ('Wagon Jaws', 10),
 ('Superfly Trip', 10),
 ('Sensibility Rear', 10),
 ('Paths Control', 10),
 ('Jawbreaker Brooklyn', 10),
 ('Stage World', 10),
 ('Santa Paris', 11),
 ('Iron Moon', 11),
 ('Twisted Pirates', 11),
 ('Rider Caddyshack', 11),
 ('Birch Antitrust', 11),
 ('Born Spinal', 12),
 ('Dangerous Uptown', 12),
 ('Crow Grease', 12),
 ('Silverado Goldfinger', 12),
 ('Temple Attraction', 12),
 ('Brannigan Sunrise', 12),
 ('Mighty Luck', 12),
 ('Massage Image', 12),
 ('Uptown Young', 12),
 ('Everyone Craft', 13),
 ('Super Wyoming', 13),
 ('Drums Dynamite', 13),
 ('Behavior Runaway', 13),
 ('Champion Flatliners', 13),
 ('Party Knock', 13),
 ('Hollywood Anonymous', 13),
 ('Bedazzled Married', 13),
 ('Opposite Necklace', 13),
 ('Mile Mulan', 13),
 ('Shanghai Tycoon', 14),
 ('Stock Glass', 14),
 ('Splash Gump', 14),
 ('Lovely Jingle', 14),
 ('Tomatoes Hellfighters', 14),
 ('Shane Darkness', 14),
 ('Necklace Outbreak', 15),
 ('Wasteland Divine', 15),
 ('Steers Armageddon', 15),
 ('Cyclone Family', 15),
 ('Hysterical Grail', 15),
 ('Monster Spartacus', 15),
 ('Boiled Dares', 15),
 ('Loser Hustler', 15),
 ('Tootsie Pilot', 15),
 ('Charade Duffel', 15),
 ('Manchurian Curtain', 15),
 ('Modern Dorado', 15),
 ('Holes Brannigan', 15),
 ('Words Hunter', 16),
 ('Worst Banger', 16),
 ('Patriot Roman', 16),
 ('Gaslight Crusade', 16),
 ('Pilot Hoosiers', 16),
 ('Watch Tracy', 16),
 ('Motions Details', 16),
 ('Wizard Coldblooded', 16),
 ('Potter Connecticut', 17),
 ('Sugar Wonka', 17),
 ('Egypt Tenenbaums', 17),
 ('Majestic Floats', 17),
 ('Musketeers Wait', 17),
 ('French Holiday', 17),
 ('Jekyll Frogmen', 17),
 ('Dying Maker', 17),
 ('Ferris Mother', 17),
 ('Lady Stage', 17),
 ('Greek Everyone', 17),
 ('Newton Labyrinth', 17),
 ('Secretary Rouge', 18),
 ('Lion Uncut', 18),
 ('Dawn Pond', 18),
 ('Instinct Airport', 18),
 ('Sweden Shining', 18),
 ('Heaven Freedom', 18),
 ('Carol Texas', 18),
 ('Pollock Deliverance', 18),
 ('Polish Brooklyn', 18),
 ('Unforgiven Zoolander', 18),
 ('Cider Desire', 19),
 ('Gables Metropolis', 19),
 ('Shawshank Bubble', 19),
 ('Fiction Christmas', 19),
 ('Disciple Mother', 19),
 ('Jedi Beneath', 19),
 ('Trojan Tomorrow', 19),
 ('Bill Others', 19),
 ('Room Roman', 20),
 ('Bringing Hysterical', 20),
 ('Pinocchio Simon', 20),
 ('Hellfighters Sierra', 20),
 ('Northwest Polish', 20),
 ('Money Harold', 20),
 ('Peak Forever', 20),
 ('Tramp Others', 20),
 ('Dalmations Sweden', 20),
 ('Chasing Fight', 20),
 ('Mourning Purple', 21),
 ('Amadeus Holy', 21),
 ('Chainsaw Uptown', 21),
 ('Coast Rainbow', 21),
 ('Fireball Philadelphia', 21),
 ('Resurrection Silverado', 21),
 ('Secret Groundhog', 21),
 ('Arizona Bang', 21),
 ('Pirates Roxanne', 21),
 ('Sleepy Japanese', 21),
 ('Open African', 21),
 ('Sabrina Midnight', 21),
 ('Egg Igby', 21),
 ('Star Operation', 21),
 ('Agent Truman', 21),
 ('Sea Virgin', 22),
 ('Snatch Slipper', 22),
 ('Dream Pickup', 22),
 ('Chicken Hellfighters', 22),
 ('Chill Luck', 22),
 ('Wonderland Christmas', 22),
 ('Queen Luke', 22),
 ('Liaisons Sweet', 22),
 ('Patton Interview', 23),
 ('Murder Antitrust', 23),
 ('Carrie Bunch', 23),
 ('Others Soup', 23),
 ('Fool Mockingbird', 23),
 ('Academy Dinosaur', 23),
 ('Trouble Date', 23),
 ('Hurricane Affair', 24),
 ('Lola Agent', 24),
 ('Center Dinosaur', 24),
 ('Wedding Apollo', 24),
 ('Slums Duck', 24),
 ('Mockingbird Hollywood', 24),
 ('Horn Working', 24),
 ('Maiden Home', 24),
 ('Bound Cheaper', 24),
 ('Trading Pinocchio', 25),
 ('Effect Gladiator', 25),
 ('Mallrats United', 25),
 ('Oscar Gold', 25),
 ('Nightmare Chill', 25),
 ('Pelican Comforts', 26),
 ('Alaska Phantom', 26),
 ('Invasion Cyclone', 27),
 ('Range Moonwalker', 27),
 ('Blackout Private', 27),
 ('Movie Shakespeare', 27),
 ('Telegraph Voyage', 27),
 ('Fatal Haunted', 28),
 ('Expendable Stallion', 28),
 ('Titans Jerk', 29),
 ('Moon Bunch', 29),
 ('Talented Homicide', 29),
 ('Suspects Quills', 30),
 ('Graffiti Love', 30),
 ('Frost Head', 30),
 ('Rush Goodfellas', 31),
 ('Goodfellas Salute', 31),
 ('Grit Clockwork', 32),
 ('Bucket Brotherhood', 34)]

In [ ]:
#**16. Muestra las películas que se ofrecen para alquilar en store_id 1 y no se ofrecen en store_id 2. **

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  film.title
FROM
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=1) AS film_store1
LEFT JOIN
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=2) AS film_store2
ON
  film_store1.film_id = film_store2.film_id
LEFT JOIN
  film
ON
  film_store2.film_id = film.film_id
WHERE
  film_store2.film_id IS NULL
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)
print(len(result))

[(None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None), (None, None)]
196

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT DISTINCT
film_id
FROM
inventory
WHERE store_id=1
EXCEPT
SELECT DISTINCT
film_id
FROM
inventory
WHERE
store_id=2

;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)
print(len(result))

[(652,), (550,), (394,), (272,), (867,), (539,), (278,), (929,), (919,), (529,), (888,), (940,), (390,), (261,), (876,), (161,), (632,), (587,), (120,), (815,), (695,), (766,), (29,), (96,), (466,), (201,), (400,), (219,), (241,), (66,), (661,), (340,), (523,), (699,), (368,), (152,), (548,), (787,), (886,), (750,), (182,), (528,), (110,), (27,), (811,), (853,), (84,), (996,), (799,), (276,), (983,), (375,), (682,), (674,), (401,), (153,), (279,), (543,), (736,), (565,), (566,), (259,), (965,), (840,), (30,), (927,), (774,), (984,), (296,), (209,), (868,), (205,), (947,), (978,), (407,), (904,), (783,), (540,), (168,), (598,), (393,), (498,), (277,), (290,), (793,), (342,), (360,), (224,), (719,), (53,), (933,), (136,), (442,), (411,), (825,), (899,), (675,), (885,), (969,), (185,), (653,), (435,), (617,), (765,), (732,), (959,), (819,), (817,), (364,), (299,), (971,), (836,), (197,), (470,), (454,), (482,), (577,), (188,), (561,), (196,), (291,), (81,), (721,), (705,), (427,), (347,), (283,), (179,), (686,), (636,), (321,), (974,), (889,), (343,), (581,), (372,), (441,), (335,), (230,), (503,), (952,), (573,), (994,), (20,), (76,), (962,), (106,), (178,), (795,), (455,), (146,), (80,), (237,), (60,), (238,), (613,), (289,), (569,), (98,), (490,), (82,), (306,), (202,), (905,), (678,), (535,), (510,), (310,), (28,), (832,), (907,), (584,), (997,), (831,), (225,), (956,), (882,), (213,), (848,), (362,), (594,), (533,), (499,), (265,), (968,), (207,), (371,), (492,), (413,), (208,), (24,), (94,), (211,), (530,), (928,), (520,)]
196

In [ ]:
#**17. Muestre las películas que se ofrecen para alquilar en cualquiera de las dos tiendas 1 y 2.**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  film.title
FROM
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=1) AS film_store1
FULL JOIN
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=2) AS film_store2
ON
  film_store1.film_id = film_store2.film_id
LEFT JOIN
  film
ON
  film_store2.film_id = film.film_id
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)
print(len(result))

[('Academy Dinosaur',), ('Ace Goldfinger',), ('Adaptation Holes',), ('Affair Prejudice',), ('African Egg',), ('Agent Truman',), ('Airplane Sierra',), ('Airport Pollock',), ('Alabama Devil',), ('Aladdin Calendar',), ('Alamo Videotape',), ('Alaska Phantom',), ('Ali Forever',), ('Alien Center',), ('Alley Evolution',), ('Alone Trip',), ('Alter Victory',), ('Amadeus Holy',), (None,), ('American Circus',), ('Amistad Midsummer',), ('Anaconda Confessions',), (None,), ('Angels Life',), ('Annie Identity',), (None,), (None,), (None,), (None,), ('Apache Divine',), ('Apocalypse Flamingos',), ('Arabia Dogma',), ('Arachnophobia Rollercoaster',), ('Arizona Bang',), ('Armageddon Lost',), ('Army Flintstones',), ('Artist Coldblooded',), ('Atlantis Cause',), ('Attacks Hate',), ('Attraction Newton',), ('Autumn Crow',), ('Baby Hall',), ('Backlash Undefeated',), ('Badman Dawn',), ('Baked Cleopatra',), ('Balloon Homeward',), ('Ballroom Mockingbird',), (None,), ('Banger Pinocchio',), ('Barbarella Streetcar',), ('Barefoot Manchurian',), ('Basic Easy',), ('Beach Heartbreakers',), ('Bear Graceland',), (None,), ('Beauty Grease',), ('Bed Highball',), ('Bedazzled Married',), ('Beethoven Exorcist',), ('Behavior Runaway',), (None,), ('Berets Agent',), ('Betrayed Rear',), ('Beverly Outlaw',), ('Bikini Borrowers',), ('Bilko Anonymous',), ('Bill Others',), ('Bingo Talented',), ('Birch Antitrust',), ('Bird Independence',), (None,), ('Birds Perdition',), ('Blackout Private',), ('Blade Polish',), (None,), (None,), (None,), ('Blues Instinct',), (None,), ('Bonnie Holocaust',), ('Boogie Amelie',), ('Born Spinal',), ('Borrowers Bedazzled',), ('Boulevard Mob',), ('Bound Cheaper',), ('Bowfinger Gables',), ('Brannigan Sunrise',), (None,), ('Breakfast Goldfinger',), (None,), ('Bride Intrigue',), (None,), ('Bringing Hysterical',), ('Brooklyn Desert',), ('Brotherhood Blanket',), ('Bubble Grosse',), ('Bucket Brotherhood',), ('Bugsy Song',), ('Bull Shawshank',), (None,), ('Bunch Minds',), ('Butterfly Chocolat',), (None,), ('Caddyshack Jedi',), ('Calendar Gunfight',), ('California Birds',), ('Camelot Vacation',), ('Campus Remember',), ('Candidate Perdition',), ('Candles Grapes',), ('Canyon Stock',), ('Caper Motions',), (None,), ('Carol Texas',), ('Carrie Bunch',), ('Casablanca Super',), ('Casper Dragonfly',), ('Cassidy Wyoming',), ('Casualties Encino',), ('Cat Coneheads',), ('Cause Date',), ('Celebrity Horn',), ('Center Dinosaur',), ('Chainsaw Uptown',), ('Chamber Italian',), ('Champion Flatliners',), ('Chance Resurrection',), (None,), ('Charade Duffel',), ('Chariots Conspiracy',), ('Chasing Fight',), ('Cheaper Clyde',), ('Chicago North',), ('Chicken Hellfighters',), ('Chill Luck',), ('Chisum Behavior',), (None,), ('Chocolat Harry',), ('Christmas Moonshine',), ('Cider Desire',), ('Cincinatti Whisperer',), (None,), (None,), ('Clash Freddy',), ('Cleopatra Devil',), ('Clerks Angels',), ('Clockwork Paradise',), ('Clones Pinocchio',), ('Closer Bang',), ('Club Graffiti',), (None,), ('Clueless Bucket',), ('Clyde Theory',), ('Coast Rainbow',), ('Coldblooded Darling',), ('Color Philadelphia',), ('Coma Head',), (None,), ('Comforts Rush',), ('Command Darling',), ('Coneheads Smoochy',), ('Confessions Maguire',), ('Confidential Interview',), ('Confused Candles',), ('Congeniality Quest',), ('Connecticut Tramp',), (None,), (None,), ('Conspiracy Spirit',), ('Contact Anonymous',), (None,), ('Conversation Downhill',), ('Core Suit',), (None,), ('Craft Outfield',), ('Cranes Reservoir',), (None,), ('Creatures Shakespeare',), ('Creepers Kane',), ('Crooked Frogmen',), ('Crossroads Casualties',), ('Crow Grease',), (None,), (None,), ('Cupboard Sinners',), ('Curtain Videotape',), (None,), (None,), ('Daisy Menagerie',), ('Dalmations Sweden',), (None,), ('Dancing Fever',), (None,), (None,), (None,), ('Darko Dorado',), (None,), ('Darn Forrester',), (None,), ('Daughter Madigan',), ('Dawn Pond',), ('Day Unfaithful',), ('Deceiver Betrayed',), (None,), ('Deer Virginian',), ('Desert Poseidon',), ('Desire Alien',), (None,), (None,), ('Destiny Saturday',), ('Details Packer',), ('Detective Vision',), ('Devil Desire',), (None,), ('Dinosaur Secretary',), ('Dirty Ace',), ('Disciple Mother',), ('Disturbing Scarface',), ('Divide Monster',), ('Divine Resurrection',), (None,), (None,), ('Dogma Family',), ('Dolls Rage',), (None,), ('Doom Dancing',), ('Doors President',), ('Dorado Notting',), ('Double Wrath',), ('Doubtfire Labyrinth',), ('Downhill Enough',), ('Dozen Lion',), ('Dracula Crystal',), ('Dragon Squad',), ('Dragonfly Strangers',), ('Dream Pickup',), ('Drifter Commandments',), ('Driver Annie',), ('Driving Polish',), ('Drop Waterfront',), ('Drumline Cyclone',), ('Drums Dynamite',), (None,), ('Dude Blindness',), (None,), ('Dumbo Lust',), ('Durham Panky',), ('Dwarfs Alter',), (None,), ('Dynamite Tarzan',), ('Eagles Panky',), ('Early Home',), ('Earring Instinct',), ('Earth Vision',), ('Easy Gladiator',), (None,), ('Effect Gladiator',), ('Egg Igby',), ('Egypt Tenenbaums',), (None,), (None,), (None,), (None,), ('Empire Malkovich',), ('Encino Elf',), ('Encounters Curtain',), (None,), ('Enemy Odds',), ('English Bulworth',), ('Enough Raging',), ('Entrapment Satisfaction',), ('Escape Metropolis',), (None,), (None,), (None,), ('Excitement Eve',), ('Exorcist Sting',), ('Expecations Natural',), ('Expendable Stallion',), (None,), ('Extraordinary Conquerer',), ('Eyes Driving',), (None,), ('Falcon Volume',), ('Family Sweet',), ('Fantasia Park',), ('Fantasy Troopers',), ('Fargo Gandhi',), ('Fatal Haunted',), (None,), ('Fellowship Autumn',), ('Ferris Mother',), ('Feud Frogmen',), (None,), ('Fiction Christmas',), ('Fiddler Lost',), ('Fidelity Devil',), ('Fight Jawbreaker',), ('Finding Anaconda',), ('Fire Wolves',), ('Fireball Philadelphia',), ('Fish Opus',), ('Flamingos Connecticut',), (None,), ('Flatliners Killer',), ('Flight Lies',), ('Flintstones Happiness',), ('Flying Hook',), ('Fool Mockingbird',), ('Forever Candidate',), ('Forrest Sons',), ('Forrester Comancheros',), ('Forward Temple',), ('Freaky Pocus',), ('Freddy Storm',), (None,), ('French Holiday',), ('Frida Slipper',), ('Frisco Forrest',), ('Frogmen Breaking',), (None,), ('Frost Head',), (None,), (None,), ('Fury Murder',), ('Gables Metropolis',), ('Galaxy Sweethearts',), (None,), ('Gandhi Kwai',), ('Gangs Pride',), ('Garden Island',), ('Gaslight Crusade',), ('Gathering Calendar',), ('Gentlemen Stage',), ('Ghost Groundhog',), ('Ghostbusters Elf',), ('Giant Troopers',), ('Gilbert Pelican',), ('Gilmore Boiled',), (None,), ('Gleaming Jawbreaker',), (None,), ('Go Purple',), (None,), ('Gold River',), ('Goldfinger Sensibility',), ('Goldmine Tycoon',), (None,), ('Goodfellas Salute',), ('Gorgeous Bingo',), (None,), (None,), ('Graduate Lord',), ('Graffiti Love',), (None,), ('Grapes Fury',), ('Grease Youth',), ('Greatest North',), ('Greedy Roots',), ('Greek Everyone',), ('Grinch Massage',), ('Grit Clockwork',), ('Groove Fiction',), ('Grosse Wonderful',), ('Groundhog Uncut',), ('Gun Bonnie',), ('Gunfight Moon',), ('Gunfighter Mussolini',), (None,), ('Half Outfield',), ('Hall Cassidy',), (None,), (None,), ('Handicap Boondock',), ('Hanging Deep',), ('Hanky October',), ('Hanover Galaxy',), ('Happiness United',), (None,), (None,), ('Harper Dying',), ('Harry Idaho',), ('Haunted Antitrust',), ('Haunting Pianist',), (None,), ('Head Stranger',), ('Heartbreakers Bright',), ('Heaven Freedom',), (None,), ('Heavyweights Beast',), (None,), ('Hellfighters Sierra',), ('High Encino',), ('Highball Potter',), ('Hills Neighbors',), ('Hobbit Alien',), ('Holes Brannigan',), ('Holiday Games',), ('Hollow Jeopardy',), ('Hollywood Anonymous',), ('Holocaust Highball',), ('Holy Tadpole',), ('Home Pity',), (None,), ('Homicide Peach',), ('Honey Ties',), ('Hook Chariots',), ('Hoosiers Birdcage',), ('Hope Tootsie',), ('Horn Working',), ('Horror Reign',), (None,), ('Hours Rage',), ('House Dynamite',), ('Human Graffiti',), ('Hunchback Impossible',), ('Hunger Roof',), (None,), (None,), ('Hurricane Affair',), ('Hustler Party',), ('Hyde Doctor',), ('Hysterical Grail',), ('Ice Crossing',), ('Idaho Love',), ('Identity Lover',), ('Idols Snatchers',), ('Igby Maker',), ('Illusion Amelie',), ('Image Princess',), (None,), (None,), ('Inch Jet',), ('Independence Hotel',), ('Indian Love',), ('Informer Double',), ('Innocent Usual',), ('Insects Stone',), ('Insider Arizona',), ('Instinct Airport',), ('Intentions Empire',), ('Interview Liaisons',), (None,), ('Intrigue Worst',), ('Invasion Cyclone',), ('Iron Moon',), (None,), ('Island Exorcist',), ('Italian African',), ('Jacket Frisco',), ('Jade Bunch',), ('Japanese Run',), ('Jason Trap',), ('Jawbreaker Brooklyn',), ('Jaws Harry',), ('Jedi Beneath',), ('Jeepers Wedding',), ('Jekyll Frogmen',), (None,), ('Jericho Mulan',), ('Jerk Paycheck',), ('Jersey Sassy',), ('Jet Neighbors',), ('Jingle Sagebrush',), ('Joon Northwest',), ('Juggler Hardly',), (None,), ('Jumping Wrath',), (None,), ('Kane Exorcist',), ('Karate Moon',), ('Kick Savannah',), (None,), (None,), ('Kiss Glory',), ('Kissing Dolls',), ('Knock Warlock',), (None,), ('Kwai Homeward',), ('Labyrinth League',), ('Lady Stage',), ('Ladybugs Armageddon',), ('Lambs Cincinatti',), ('Language Cowboy',), (None,), ('Lawrence Love',), ('League Hellfighters',), ('Leathernecks Dwarfs',), ('Lebowski Soldiers',), ('Legally Secretary',), ('Legend Jedi',), ('Lesson Cleopatra',), ('Liaisons Sweet',), ('Liberty Magnificent',), (None,), ('Lies Treatment',), ('Life Twisted',), (None,), ('Lion Uncut',), ('Loathing Legally',), ('Lock Rear',), ('Lola Agent',), (None,), (None,), (None,), ('Lose Inch',), ('Loser Hustler',), (None,), ('Louisiana Harry',), (None,), ('Lovely Jingle',), ('Lover Truman',), ('Loverboy Attacks',), (None,), (None,), ('Luke Mummy',), ('Lust Lock',), (None,), ('Madison Trap',), ('Madness Attacks',), ('Madre Gables',), ('Magic Mallrats',), (None,), ('Magnolia Forrester',), (None,), ('Maiden Home',), ('Majestic Floats',), ('Maker Gables',), ('Malkovich Pet',), ('Mallrats United',), ('Maltese Hope',), ('Manchurian Curtain',), ('Mannequin Worst',), ('Married Go',), ('Mars Roman',), (None,), ('Masked Bubble',), ('Massacre Usual',), ('Massage Image',), (None,), (None,), ('Meet Chocolate',), ('Memento Zoolander',), (None,), ('Mermaid Insects',), ('Metal Armageddon',), ('Metropolis Coma',), (None,), ('Midnight Westward',), ('Midsummer Groundhog',), ('Mighty Luck',), (None,), ('Million Ace',), ('Minds Truman',), ('Mine Titans',), (None,), ('Miracle Virtual',), ('Mission Zoolander',), (None,), ('Mob Duffel',), ('Mockingbird Hollywood',), (None,), ('Model Fish',), ('Modern Dorado',), ('Money Harold',), ('Monsoon Cause',), ('Monster Spartacus',), ('Monterey Labyrinth',), (None,), ('Moon Bunch',), ('Moonshine Cabin',), ('Moonwalker Fool',), (None,), ('Mother Oleander',), ('Motions Details',), ('Moulin Wake',), ('Mourning Purple',), ('Movie Shakespeare',), ('Mulan Moon',), ('Mulholland Beast',), ('Mummy Creatures',), ('Murder Antitrust',), ('Muscle Bright',), ('Music Boondock',), ('Musketeers Wait',), ('Mussolini Spoilers',), (None,), ('Name Detective',), ('Nash Chocolat',), ('National Story',), (None,), ('Necklace Outbreak',), ('Neighbors Charade',), ('Nemo Campus',), ('Network Peak',), ('Newsies Story',), ('Newton Labyrinth',), ('Nightmare Chill',), ('None Spiking',), ('Noon Papi',), ('North Tequila',), ('Northwest Polish',), ('Notorious Reunion',), ('Notting Speakeasy',), ('Novocaine Flight',), (None,), ('October Submarine',), ('Odds Boogie',), ('Oklahoma Jumanji',), (None,), ('Open African',), ('Operation Operation',), ('Opposite Necklace',), ('Opus Ice',), ('Orange Grapes',), ('Orient Closer',), ('Oscar Gold',), ('Others Soup',), ('Outbreak Divine',), ('Outfield Massacre',), ('Outlaw Hanky',), ('Oz Liaisons',), ('Pacific Amistad',), ('Packer Madigan',), (None,), (None,), ('Panky Submarine',), ('Panther Reds',), ('Papi Necklace',), ('Paradise Sabrina',), ('Paris Weekend',), ('Park Citizen',), ('Party Knock',), (None,), ('Paths Control',), ('Patient Sister',), ('Patriot Roman',), ('Patton Interview',), ('Paycheck Wait',), ('Peach Innocent',), ('Peak Forever',), ('Pelican Comforts',), ('Perfect Groove',), ('Personal Ladybugs',), (None,), (None,), ('Philadelphia Wife',), ('Pianist Outfield',), (None,), ('Pilot Hoosiers',), ('Pinocchio Simon',), ('Pirates Roxanne',), (None,), ('Pity Bound',), ('Pizza Jumanji',), ('Platoon Instinct',), (None,), ('Pocus Pulp',), ('Polish Brooklyn',), ('Pollock Deliverance',), ('Pond Seattle',), ('Poseidon Forever',), ('Potluck Mixed',), ('Potter Connecticut',), ('Prejudice Oleander',), (None,), ('Pride Alamo',), ('Primary Glass',), ('Princess Giant',), (None,), ('Prix Undefeated',), ('Pulp Beverly',), ('Punk Divorce',), ('Pure Runner',), (None,), ('Queen Luke',), ('Quest Mussolini',), ('Quills Bull',), ('Racer Egg',), ('Rage Games',), ('Raging Airplane',), ('Random Go',), ('Range Moonwalker',), ('Reap Unfaithful',), ('Rear Trading',), ('Rebel Airport',), (None,), ('Redemption Comforts',), (None,), ('Reef Salute',), ('Reign Gentlemen',), ('Remember Diary',), ('Requiem Tycoon',), ('Reservoir Adaptation',), ('Resurrection Silverado',), ('Reunion Witches',), ('Rider Caddyshack',), ('Ridgemont Submarine',), ('Right Cranes',), (None,), ('River Outlaw',), ('Road Roxanne',), ('Robbers Joon',), (None,), ('Rock Instinct',), ('Rocketeer Mother',), ('Rocky War',), ('Rollercoaster Bringing',), ('Roman Punk',), ('Room Roman',), ('Roots Remember',), ('Roses Treasure',), ('Rouge Squad',), ('Roxanne Rebel',), ('Rugrats Shakespeare',), ('Rules Human',), (None,), ('Runaway Tenenbaums',), ('Runner Madigan',), ('Rush Goodfellas',), ('Rushmore Mermaid',), ('Sabrina Midnight',), ('Saddle Antitrust',), ('Sagebrush Clueless',), ('Saints Bride',), ('Salute Apollo',), ('Samurai Lion',), ('Santa Paris',), ('Sassy Packer',), ('Satisfaction Confidential',), ('Saturday Lambs',), (None,), (None,), ('Scalawag Duck',), ('Scarface Bang',), ('School Jacket',), ('Scissorhands Slums',), ('Scorpion Apollo',), ('Sea Virgin',), ('Seabiscuit Punk',), (None,), ('Seattle Expecations',), ('Secret Groundhog',), ('Secretary Rouge',), ('Secrets Paradise',), ('Sense Greek',), ('Sensibility Rear',), ('Seven Swarm',), ('Shakespeare Saddle',), (None,), ('Shanghai Tycoon',), ('Shawshank Bubble',), ('Shepherd Midsummer',), (None,), ('Ship Wonderland',), ('Shock Cabin',), ('Shootist Superfly',), ('Show Lord',), ('Shrek License',), (None,), ('Side Ark',), (None,), ('Sierra Divide',), ('Silence Kane',), ('Silverado Goldfinger',), (None,), ('Sinners Atlantis',), ('Slacker Liaisons',), ('Sleeping Suspects',), ('Sleepless Monsoon',), ('Sleepy Japanese',), ('Sleuth Orient',), ('Sling Luke',), ('Slipper Fidelity',), ('Slums Duck',), (None,), ('Smoking Barbarella',), ('Smoochy Control',), ('Snatch Slipper',), (None,), ('Snowman Rollercoaster',), (None,), ('Something Duck',), (None,), ('Sons Interview',), ('Sorority Queen',), ('Soup Wisdom',), ('South Wait',), ('Spartacus Cheaper',), (None,), ('Speed Suit',), ('Spice Sorority',), ('Spiking Element',), ('Spinal Rocky',), ('Spirit Flintstones',), (None,), (None,), ('Splendor Patton',), ('Spoilers Hellfighters',), ('Spy Mile',), (None,), ('Stage World',), ('Stagecoach Armageddon',), ('Stallion Sundance',), (None,), ('Star Operation',), ('State Wasteland',), ('Steel Santa',), ('Steers Armageddon',), ('Stepmom Dream',), ('Sting Personal',), ('Stock Glass',), (None,), ('Storm Happiness',), ('Story Side',), ('Straight Hours',), ('Strangelove Desire',), (None,), ('Strangers Graffiti',), ('Streak Ridgemont',), ('Streetcar Intentions',), ('Strictly Scarface',), ('Submarine Bed',), ('Sugar Wonka',), ('Suit Walls',), ('Summer Scarface',), ('Sun Confessions',), ('Sundance Invasion',), ('Sunrise League',), ('Sunset Racer',), (None,), (None,), ('Suspects Quills',), ('Swarm Gold',), ('Sweden Shining',), ('Sweet Brotherhood',), ('Sweethearts Suspects',), ('Talented Homicide',), (None,), ('Taxi Kick',), ('Teen Apollo',), ('Telegraph Voyage',), ('Telemark Heartbreakers',), ('Temple Attraction',), (None,), ('Tequila Past',), ('Terminator Club',), (None,), (None,), ('Thief Pelican',), (None,), (None,), ('Tights Dawn',), ('Timberland Sky',), ('Titanic Boondock',), ('Titans Jerk',), ('Tomatoes Hellfighters',), ('Tomorrow Hustler',), ('Tootsie Pilot',), ('Torque Bound',), ('Tourist Pelican',), (None,), ('Town Ark',), ('Tracy Cider',), ('Trading Pinocchio',), ('Traffic Hobbit',), (None,), (None,), ('Tramp Others',), (None,), ('Trap Guys',), ('Treatment Jekyll',), ('Trip Newton',), ('Trojan Tomorrow',), ('Troopers Metal',), ('Trouble Date',), ('Truman Crazy',), ('Turn Star',), ('Tuxedo Mile',), ('Twisted Pirates',), (None,), ('Unbreakable Karate',), ('Uncut Suicides',), ('Undefeated Dalmations',), ('Unfaithful Kill',), ('Unforgiven Zoolander',), ('United Pilot',), ('Untouchables Sunrise',), (None,), (None,), (None,), ('Vacation Boondock',), ('Valentine Vanishing',), ('Valley Packer',), (None,), ('Vanilla Day',), ('Vanished Garden',), ('Vanishing Rocky',), ('Varsity Trip',), ('Velvet Terminator',), ('Vertigo Northwest',), (None,), ('Videotape Arsenic',), ('Vietnam Smoochy',), ('Virgin Daisy',), ('Virginian Pluto',), ('Virtual Spoilers',), (None,), ('Voice Peach',), ('Volcano Texas',), ('Voyage Legally',), (None,), ('Wait Cider',), (None,), ('War Notting',), ('Wardrobe Phantom',), (None,), ('Wars Pluto',), ('Wash Heavenly',), (None,), ('Watch Tracy',), ('Waterfront Deliverance',), (None,), ('Wedding Apollo',), ('Weekend Personal',), (None,), (None,), ('Westward Seabiscuit',), (None,), ('Whisperer Giant',), ('Wife Turn',), (None,), ('Willow Tracy',), ('Wind Phantom',), ('Window Side',), (None,), ('Witches Panic',), ('Wizard Coldblooded',), ('Wolves Desire',), ('Women Dorado',), (None,), (None,), ('Wonderland Christmas',), ('Wonka Sea',), ('Words Hunter',), ('Worker Tarzan',), ('Working Microcosmos',), ('World Leathernecks',), ('Worst Banger',), ('Wrath Mile',), ('Wrong Behavior',), (None,), ('Yentl Idaho',), (None,), (None,), ('Zhivago Core',), ('Zoolander Fiction',), ('Zorro Ark',)]
958

In [ ]:
#**18. Muestra los títulos de las películas que se ofrecen en ambas tiendas al mismo tiempo**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  film.title
FROM
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=1) AS film_store1
JOIN
  (SELECT DISTINCT film_id FROM inventory WHERE store_id=2) AS film_store2
ON
  film_store1.film_id = film_store2.film_id
JOIN
  film
ON
  film_store2.film_id = film.film_id
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)
print(len(result))

[('Academy Dinosaur',), ('Affair Prejudice',), ('Agent Truman',), ('Airplane Sierra',), ('Alabama Devil',), ('Aladdin Calendar',), ('Alamo Videotape',), ('Alaska Phantom',), ('Alien Center',), ('Alley Evolution',), ('Alone Trip',), ('Alter Victory',), ('Amadeus Holy',), ('American Circus',), ('Amistad Midsummer',), ('Anaconda Confessions',), ('Angels Life',), ('Annie Identity',), ('Apache Divine',), ('Arachnophobia Rollercoaster',), ('Arizona Bang',), ('Armageddon Lost',), ('Atlantis Cause',), ('Attacks Hate',), ('Attraction Newton',), ('Backlash Undefeated',), ('Badman Dawn',), ('Baked Cleopatra',), ('Balloon Homeward',), ('Banger Pinocchio',), ('Barbarella Streetcar',), ('Barefoot Manchurian',), ('Basic Easy',), ('Bear Graceland',), ('Beauty Grease',), ('Bedazzled Married',), ('Berets Agent',), ('Betrayed Rear',), ('Beverly Outlaw',), ('Bikini Borrowers',), ('Bill Others',), ('Bingo Talented',), ('Birch Antitrust',), ('Birds Perdition',), ('Blackout Private',), ('Blade Polish',), ('Blues Instinct',), ('Boogie Amelie',), ('Borrowers Bedazzled',), ('Boulevard Mob',), ('Bound Cheaper',), ('Bowfinger Gables',), ('Breakfast Goldfinger',), ('Bride Intrigue',), ('Bringing Hysterical',), ('Brooklyn Desert',), ('Brotherhood Blanket',), ('Bucket Brotherhood',), ('Bull Shawshank',), ('Butterfly Chocolat',), ('Calendar Gunfight',), ('Camelot Vacation',), ('Campus Remember',), ('Candidate Perdition',), ('Candles Grapes',), ('Canyon Stock',), ('Caper Motions',), ('Carol Texas',), ('Carrie Bunch',), ('Casablanca Super',), ('Cat Coneheads',), ('Cause Date',), ('Celebrity Horn',), ('Center Dinosaur',), ('Chainsaw Uptown',), ('Chamber Italian',), ('Chance Resurrection',), ('Chariots Conspiracy',), ('Chasing Fight',), ('Cheaper Clyde',), ('Chicago North',), ('Chicken Hellfighters',), ('Chill Luck',), ('Chocolat Harry',), ('Christmas Moonshine',), ('Cider Desire',), ('Cincinatti Whisperer',), ('Clash Freddy',), ('Cleopatra Devil',), ('Clones Pinocchio',), ('Closer Bang',), ('Club Graffiti',), ('Clueless Bucket',), ('Coast Rainbow',), ('Coldblooded Darling',), ('Color Philadelphia',), ('Coma Head',), ('Comforts Rush',), ('Command Darling',), ('Coneheads Smoochy',), ('Confessions Maguire',), ('Confidential Interview',), ('Confused Candles',), ('Congeniality Quest',), ('Contact Anonymous',), ('Conversation Downhill',), ('Core Suit',), ('Craft Outfield',), ('Creatures Shakespeare',), ('Crooked Frogmen',), ('Crossroads Casualties',), ('Crow Grease',), ('Cupboard Sinners',), ('Curtain Videotape',), ('Dalmations Sweden',), ('Dancing Fever',), ('Darn Forrester',), ('Dawn Pond',), ('Day Unfaithful',), ('Deceiver Betrayed',), ('Deer Virginian',), ('Desert Poseidon',), ('Destiny Saturday',), ('Details Packer',), ('Detective Vision',), ('Devil Desire',), ('Dinosaur Secretary',), ('Dirty Ace',), ('Disciple Mother',), ('Disturbing Scarface',), ('Divide Monster',), ('Dogma Family',), ('Doom Dancing',), ('Doors President',), ('Dorado Notting',), ('Double Wrath',), ('Downhill Enough',), ('Dracula Crystal',), ('Dragonfly Strangers',), ('Dream Pickup',), ('Drifter Commandments',), ('Driver Annie',), ('Driving Polish',), ('Durham Panky',), ('Dynamite Tarzan',), ('Eagles Panky',), ('Earring Instinct',), ('Earth Vision',), ('Easy Gladiator',), ('Effect Gladiator',), ('Egg Igby',), ('Egypt Tenenbaums',), ('Empire Malkovich',), ('Encino Elf',), ('Encounters Curtain',), ('Enemy Odds',), ('English Bulworth',), ('Enough Raging',), ('Entrapment Satisfaction',), ('Escape Metropolis',), ('Excitement Eve',), ('Exorcist Sting',), ('Expecations Natural',), ('Expendable Stallion',), ('Eyes Driving',), ('Falcon Volume',), ('Family Sweet',), ('Fantasia Park',), ('Fantasy Troopers',), ('Fargo Gandhi',), ('Fatal Haunted',), ('Fellowship Autumn',), ('Ferris Mother',), ('Feud Frogmen',), ('Fiction Christmas',), ('Fidelity Devil',), ('Fight Jawbreaker',), ('Fireball Philadelphia',), ('Fish Opus',), ('Flamingos Connecticut',), ('Flatliners Killer',), ('Flintstones Happiness',), ('Flying Hook',), ('Fool Mockingbird',), ('Forrest Sons',), ('Forrester Comancheros',), ('Forward Temple',), ('Freaky Pocus',), ('Freddy Storm',), ('French Holiday',), ('Frida Slipper',), ('Frost Head',), ('Fury Murder',), ('Gables Metropolis',), ('Galaxy Sweethearts',), ('Gangs Pride',), ('Garden Island',), ('Gaslight Crusade',), ('Gentlemen Stage',), ('Ghost Groundhog',), ('Giant Troopers',), ('Gilmore Boiled',), ('Gleaming Jawbreaker',), ('Go Purple',), ('Gold River',), ('Goldfinger Sensibility',), ('Goldmine Tycoon',), ('Goodfellas Salute',), ('Gorgeous Bingo',), ('Graduate Lord',), ('Graffiti Love',), ('Grapes Fury',), ('Grease Youth',), ('Greatest North',), ('Greek Everyone',), ('Grinch Massage',), ('Grit Clockwork',), ('Groove Fiction',), ('Groundhog Uncut',), ('Gun Bonnie',), ('Gunfight Moon',), ('Gunfighter Mussolini',), ('Half Outfield',), ('Hall Cassidy',), ('Handicap Boondock',), ('Hanky October',), ('Harper Dying',), ('Harry Idaho',), ('Haunting Pianist',), ('Head Stranger',), ('Heartbreakers Bright',), ('Heaven Freedom',), ('Heavyweights Beast',), ('Hellfighters Sierra',), ('High Encino',), ('Highball Potter',), ('Hills Neighbors',), ('Hobbit Alien',), ('Holes Brannigan',), ('Hollywood Anonymous',), ('Holocaust Highball',), ('Homicide Peach',), ('Honey Ties',), ('Hope Tootsie',), ('Horn Working',), ('Horror Reign',), ('Hours Rage',), ('House Dynamite',), ('Human Graffiti',), ('Hunchback Impossible',), ('Hunger Roof',), ('Hurricane Affair',), ('Hustler Party',), ('Hyde Doctor',), ('Hysterical Grail',), ('Ice Crossing',), ('Idaho Love',), ('Idols Snatchers',), ('Igby Maker',), ('Image Princess',), ('Inch Jet',), ('Independence Hotel',), ('Indian Love',), ('Innocent Usual',), ('Insects Stone',), ('Insider Arizona',), ('Instinct Airport',), ('Intentions Empire',), ('Interview Liaisons',), ('Intrigue Worst',), ('Invasion Cyclone',), ('Island Exorcist',), ('Jacket Frisco',), ('Jason Trap',), ('Jaws Harry',), ('Jedi Beneath',), ('Jeepers Wedding',), ('Jekyll Frogmen',), ('Jericho Mulan',), ('Jerk Paycheck',), ('Jet Neighbors',), ('Joon Northwest',), ('Juggler Hardly',), ('Jumping Wrath',), ('Karate Moon',), ('Kick Savannah',), ('Kiss Glory',), ('Kissing Dolls',), ('Knock Warlock',), ('Kwai Homeward',), ('Lady Stage',), ('Lawrence Love',), ('League Hellfighters',), ('Lebowski Soldiers',), ('Liaisons Sweet',), ('Lies Treatment',), ('Lion Uncut',), ('Loathing Legally',), ('Lola Agent',), ('Lose Inch',), ('Louisiana Harry',), ('Lovely Jingle',), ('Lust Lock',), ('Madison Trap',), ('Madness Attacks',), ('Magnolia Forrester',), ('Maiden Home',), ('Malkovich Pet',), ('Mallrats United',), ('Maltese Hope',), ('Manchurian Curtain',), ('Married Go',), ('Mars Roman',), ('Masked Bubble',), ('Massacre Usual',), ('Meet Chocolate',), ('Memento Zoolander',), ('Mermaid Insects',), ('Metal Armageddon',), ('Metropolis Coma',), ('Midnight Westward',), ('Midsummer Groundhog',), ('Million Ace',), ('Minds Truman',), ('Mine Titans',), ('Mission Zoolander',), ('Mockingbird Hollywood',), ('Money Harold',), ('Monster Spartacus',), ('Moon Bunch',), ('Moonshine Cabin',), ('Mother Oleander',), ('Motions Details',), ('Moulin Wake',), ('Mourning Purple',), ('Movie Shakespeare',), ('Mummy Creatures',), ('Murder Antitrust',), ('Muscle Bright',), ('Music Boondock',), ('Musketeers Wait',), ('Name Detective',), ('National Story',), ('Neighbors Charade',), ('Nemo Campus',), ('Network Peak',), ('Newton Labyrinth',), ('Nightmare Chill',), ('None Spiking',), ('Northwest Polish',), ('Novocaine Flight',), ('Open African',), ('Operation Operation',), ('Orange Grapes',), ('Orient Closer',), ('Oscar Gold',), ('Others Soup',), ('Outbreak Divine',), ('Outfield Massacre',), ('Outlaw Hanky',), ('Oz Liaisons',), ('Pacific Amistad',), ('Packer Madigan',), ('Panky Submarine',), ('Panther Reds',), ('Paradise Sabrina',), ('Party Knock',), ('Paths Control',), ('Patient Sister',), ('Patriot Roman',), ('Patton Interview',), ('Paycheck Wait',), ('Peach Innocent',), ('Peak Forever',), ('Pelican Comforts',), ('Perfect Groove',), ('Personal Ladybugs',), ('Philadelphia Wife',), ('Pianist Outfield',), ('Pilot Hoosiers',), ('Pinocchio Simon',), ('Pirates Roxanne',), ('Pity Bound',), ('Pocus Pulp',), ('Pollock Deliverance',), ('Pond Seattle',), ('Poseidon Forever',), ('Potter Connecticut',), ('Prejudice Oleander',), ('Pride Alamo',), ('Primary Glass',), ('Princess Giant',), ('Pulp Beverly',), ('Pure Runner',), ('Queen Luke',), ('Quest Mussolini',), ('Quills Bull',), ('Racer Egg',), ('Rage Games',), ('Range Moonwalker',), ('Reap Unfaithful',), ('Rear Trading',), ('Redemption Comforts',), ('Reef Salute',), ('Reign Gentlemen',), ('Remember Diary',), ('Requiem Tycoon',), ('Resurrection Silverado',), ('Reunion Witches',), ('Ridgemont Submarine',), ('River Outlaw',), ('Road Roxanne',), ('Robbers Joon',), ('Rock Instinct',), ('Rocketeer Mother',), ('Rocky War',), ('Roman Punk',), ('Room Roman',), ('Roots Remember',), ('Roses Treasure',), ('Rouge Squad',), ('Roxanne Rebel',), ('Rugrats Shakespeare',), ('Rules Human',), ('Rush Goodfellas',), ('Sabrina Midnight',), ('Sagebrush Clueless',), ('Salute Apollo',), ('Samurai Lion',), ('Satisfaction Confidential',), ('Saturday Lambs',), ('Scalawag Duck',), ('Scarface Bang',), ('Scorpion Apollo',), ('Sea Virgin',), ('Seabiscuit Punk',), ('Seattle Expecations',), ('Secret Groundhog',), ('Secretary Rouge',), ('Secrets Paradise',), ('Shakespeare Saddle',), ('Shanghai Tycoon',), ('Shawshank Bubble',), ('Shepherd Midsummer',), ('Ship Wonderland',), ('Shock Cabin',), ('Shootist Superfly',), ('Show Lord',), ('Side Ark',), ('Sierra Divide',), ('Silence Kane',), ('Silverado Goldfinger',), ('Sinners Atlantis',), ('Slacker Liaisons',), ('Sleeping Suspects',), ('Sleepless Monsoon',), ('Sleepy Japanese',), ('Sleuth Orient',), ('Slums Duck',), ('Smoking Barbarella',), ('Snatch Slipper',), ('Snowman Rollercoaster',), ('Something Duck',), ('Sons Interview',), ('South Wait',), ('Spice Sorority',), ('Spinal Rocky',), ('Splendor Patton',), ('Spy Mile',), ('Stagecoach Armageddon',), ('Star Operation',), ('State Wasteland',), ('Steel Santa',), ('Steers Armageddon',), ('Stepmom Dream',), ('Sting Personal',), ('Storm Happiness',), ('Story Side',), ('Straight Hours',), ('Strangelove Desire',), ('Streak Ridgemont',), ('Streetcar Intentions',), ('Strictly Scarface',), ('Sugar Wonka',), ('Suit Walls',), ('Summer Scarface',), ('Sun Confessions',), ('Sundance Invasion',), ('Sunrise League',), ('Suspects Quills',), ('Swarm Gold',), ('Sweden Shining',), ('Sweethearts Suspects',), ('Talented Homicide',), ('Taxi Kick',), ('Telegraph Voyage',), ('Telemark Heartbreakers',), ('Thief Pelican',), ('Tights Dawn',), ('Timberland Sky',), ('Titanic Boondock',), ('Titans Jerk',), ('Tomatoes Hellfighters',), ('Tomorrow Hustler',), ('Tootsie Pilot',), ('Torque Bound',), ('Tourist Pelican',), ('Town Ark',), ('Tracy Cider',), ('Trading Pinocchio',), ('Tramp Others',), ('Trap Guys',), ('Trip Newton',), ('Trojan Tomorrow',), ('Troopers Metal',), ('Trouble Date',), ('Truman Crazy',), ('Turn Star',), ('Tuxedo Mile',), ('Unbreakable Karate',), ('Uncut Suicides',), ('Undefeated Dalmations',), ('Unforgiven Zoolander',), ('United Pilot',), ('Vacation Boondock',), ('Valley Packer',), ('Vanishing Rocky',), ('Varsity Trip',), ('Velvet Terminator',), ('Videotape Arsenic',), ('Vietnam Smoochy',), ('Virgin Daisy',), ('Virginian Pluto',), ('Voice Peach',), ('Volcano Texas',), ('Voyage Legally',), ('Wait Cider',), ('War Notting',), ('Wardrobe Phantom',), ('Wash Heavenly',), ('Watch Tracy',), ('Waterfront Deliverance',), ('Wedding Apollo',), ('Weekend Personal',), ('Westward Seabiscuit',), ('Whisperer Giant',), ('Wife Turn',), ('Willow Tracy',), ('Wind Phantom',), ('Witches Panic',), ('Wizard Coldblooded',), ('Wolves Desire',), ('Women Dorado',), ('Wonderland Christmas',), ('Wonka Sea',), ('Words Hunter',), ('Worker Tarzan',), ('Working Microcosmos',), ('Worst Banger',), ('Wrong Behavior',), ('Yentl Idaho',), ('Zoolander Fiction',), ('Zorro Ark',)]
563

In [ ]:
#**19. Para cada tienda, muestre el número de clientes que son miembros de esa tienda**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  store_id, count(customer_id)
FROM
  customer
GROUP BY
  1;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[(1, 326), (2, 273)]

In [ ]:
#**20. Muestra el título de la película más alquilada en la tienda con store_id 1**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  inventory.film_id, count(rental.rental_id)
FROM
  rental
JOIN
  inventory
ON
  inventory.inventory_id = rental.inventory_id
wHERE
  inventory.store_id = 1
GROUP BY
  inventory.film_id
ORDER BY 2 DESC
LIMIT 1
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[(535, 20)]

In [ ]:
##**21. Cuántas películas aún no se ofrecen para alquilar en las tiendas. Hay dos tiendas solo 1 y 2**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
  film.title, inventory.store_id
FROM
  film
LEFT JOIN
  inventory
ON
  inventory.film_id = film.film_id
WHERE
  inventory.film_id IS NULL
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone()
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[('Alice Fantasia', None),
 ('Apollo Teen', None),
 ('Argonauts Town', None),
 ('Ark Ridgemont', None),
 ('Arsenic Independence', None),
 ('Boondock Ballroom', None),
 ('Butch Panther', None),
 ('Catch Amistad', None),
 ('Chinatown Gladiator', None),
 ('Chocolate Duck', None),
 ('Commandments Express', None),
 ('Crossing Divorce', None),
 ('Crowds Telemark', None),
 ('Crystal Breaking', None),
 ('Dazed Punk', None),
 ('Deliverance Mulholland', None),
 ('Firehouse Vietnam', None),
 ('Floats Garden', None),
 ('Frankenstein Stranger', None),
 ('Gladiator Westward', None),
 ('Gump Date', None),
 ('Hate Handicap', None),
 ('Hocus Frida', None),
 ('Kentuckian Giant', None),
 ('Kill Brotherhood', None),
 ('Muppet Mile', None),
 ('Order Betrayed', None),
 ('Pearl Destiny', None),
 ('Perdition Fargo', None),
 ('Psycho Shrunk', None),
 ('Raiders Antitrust', None),
 ('Rainbow Shock', None),
 ('Roof Champion', None),
 ('Sister Freddy', None),
 ('Sky Miracle', None),
 ('Suicides Silence', None),
 ('Tadpole Park', None),
 ('Treasure Command', None),
 ('Villain Desperate', None),
 ('Volume House', None),
 ('Wake Jaws', None),
 ('Walls Artist', None)]

In [ ]:
##**22. Muestre los customer_id para aquellos clientes que alquilaron un DVD de películas más de una vez.**
#Para responder a esta pregunta, primero debemos conocer los film_ids que alquiló cada cliente.

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 rental.customer_id, inventory.film_id, COUNT(rental.rental_id)
FROM
  rental
JOIN
  inventory
ON
  inventory.inventory_id = rental.inventory_id
GROUP BY
  1,2
HAVING COUNT(rental.rental_id) > 1;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
print(result)
print(len(result))

[(513, 854, 2), (280, 911, 2), (245, 254, 2), (516, 646, 2), (562, 311, 2), (296, 838, 2), (260, 267, 2), (366, 307, 2), (468, 972, 2), (408, 373, 2), (287, 115, 2), (414, 800, 2), (47, 21, 2), (270, 756, 2), (64, 562, 2), (463, 140, 2), (391, 114, 2), (169, 172, 2), (278, 388, 2), (323, 303, 2), (594, 214, 2), (582, 625, 2), (142, 973, 2), (476, 78, 2), (46, 979, 2), (36, 462, 2), (495, 843, 2), (237, 63, 2), (72, 303, 2), (412, 915, 2), (47, 307, 2), (573, 12, 2), (403, 460, 2), (198, 966, 2), (6, 807, 2), (196, 326, 2), (356, 207, 2), (251, 972, 2), (122, 611, 2), (560, 84, 2), (244, 11, 2), (209, 381, 2), (440, 12, 2), (181, 103, 2), (234, 170, 2), (502, 434, 2), (372, 579, 2), (334, 689, 2), (249, 535, 2), (569, 753, 2), (56, 869, 2), (1, 663, 2), (557, 873, 2), (321, 893, 2), (18, 995, 2), (384, 143, 2), (132, 484, 2), (467, 141, 2), (452, 353, 2), (421, 521, 2), (74, 951, 2), (458, 942, 2), (137, 215, 2), (251, 445, 2), (464, 360, 2), (525, 86, 2), (526, 966, 2), (39, 738, 2), (43, 785, 2), (12, 737, 2), (511, 649, 2), (313, 109, 2), (380, 245, 2), (447, 555, 2), (42, 49, 2), (366, 890, 2), (206, 441, 2), (8, 554, 2), (273, 603, 2), (122, 233, 3), (482, 542, 2), (407, 387, 2), (319, 271, 2), (298, 21, 2), (119, 73, 2), (371, 603, 2), (368, 504, 2), (528, 502, 2), (117, 961, 2), (59, 388, 2), (322, 298, 2), (482, 500, 2), (163, 25, 2), (167, 987, 2), (415, 869, 2), (409, 200, 2), (373, 820, 2), (438, 563, 2), (503, 690, 2), (214, 648, 2), (119, 773, 2), (158, 206, 2), (543, 880, 2), (579, 911, 2), (405, 741, 2), (451, 437, 2), (21, 531, 2), (594, 158, 2), (417, 953, 2), (30, 945, 2), (245, 747, 2), (84, 856, 2), (460, 753, 2), (30, 361, 2), (160, 576, 2), (259, 131, 2), (325, 575, 2), (482, 861, 2), (583, 676, 2), (80, 95, 2), (111, 4, 2), (27, 280, 2), (190, 536, 2), (193, 865, 2), (171, 295, 2), (269, 341, 2), (73, 929, 2), (316, 165, 2), (422, 985, 2), (302, 568, 2), (23, 602, 2), (173, 645, 2), (237, 581, 2), (512, 127, 2), (566, 644, 2), (118, 746, 2), (40, 941, 2), (314, 973, 2), (314, 111, 3), (563, 737, 2), (129, 231, 2), (122, 643, 2), (55, 596, 2), (513, 814, 2), (99, 698, 2), (558, 518, 2), (7, 880, 2), (552, 131, 2), (211, 805, 2), (342, 970, 2), (532, 944, 2), (510, 745, 2), (293, 723, 2), (381, 181, 2), (386, 220, 2), (335, 440, 2), (348, 220, 2), (21, 952, 2), (437, 302, 2), (30, 280, 2), (87, 863, 2), (208, 571, 2), (541, 489, 2), (591, 803, 2), (58, 242, 2), (334, 892, 2), (358, 926, 2), (563, 527, 2), (371, 367, 2), (317, 322, 3), (384, 467, 2), (305, 595, 2), (1, 317, 2), (446, 486, 2), (186, 341, 2), (410, 941, 2), (181, 856, 2), (108, 1000, 2), (242, 481, 2), (188, 638, 2), (220, 111, 2), (90, 979, 2), (256, 906, 2), (42, 869, 2), (246, 738, 2), (499, 588, 2), (322, 619, 2), (375, 253, 2), (491, 263, 2), (376, 228, 3), (332, 665, 2), (349, 486, 2), (348, 697, 2), (469, 646, 2), (19, 875, 2), (405, 629, 2), (178, 973, 2), (122, 555, 2), (276, 807, 2), (476, 273, 2), (113, 945, 2), (469, 595, 2), (6, 285, 2), (310, 120, 2), (379, 561, 2), (54, 953, 2), (439, 574, 2), (70, 563, 2), (72, 76, 2), (15, 353, 2), (15, 116, 2), (571, 113, 2)]
212

In [ ]:
#**23. Muestra la cantidad de películas alquiladas en cada clasificación.**
#Para responder a esta pregunta, primero debemos conocer los ID de película que se alquilaron (unir tablas de alquiler e inventario) y las calificaciones de cada película (unir tabla de películas).

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.rating, COUNT (rental.rental_date)
FROM
  film
FULL JOIN
  inventory
ON
  film.film_id = inventory.film_id
FULL JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
WHERE
  rental.rental_date IS NOT NULL
GROUP BY
  1
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[('G', 2773), ('R', 3181), ('NC-17', 3293), ('PG', 3212), ('PG-13', 3585)]

In [ ]:
#Si en lugar de calcular la cantidad de alquileres por categoría calculo la cantidad de películas por categoría:

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 film.rating, COUNT (DISTINCT film.title)
FROM
  film
FULL JOIN
  inventory
ON
  film.film_id = inventory.film_id
FULL JOIN
  rental
ON
  rental.inventory_id = inventory.inventory_id
WHERE
  rental.rental_date IS NOT NULL
GROUP BY
  1
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[('G', 171), ('PG', 183), ('PG-13', 213), ('R', 189), ('NC-17', 202)]

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
select count (distinct film.film_id)
from film
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[(1000,)]

[('Academy Dinosaur',),
 ('Alice Fantasia',),
 ('Apollo Teen',),
 ('Argonauts Town',),
 ('Ark Ridgemont',),
 ('Arsenic Independence',),
 ('Boondock Ballroom',),
 ('Butch Panther',),
 ('Catch Amistad',),
 ('Chinatown Gladiator',),
 ('Chocolate Duck',),
 ('Commandments Express',),
 ('Crossing Divorce',),
 ('Crowds Telemark',),
 ('Crystal Breaking',),
 ('Dazed Punk',),
 ('Deliverance Mulholland',),
 ('Firehouse Vietnam',),
 ('Floats Garden',),
 ('Frankenstein Stranger',),
 ('Gladiator Westward',),
 ('Gump Date',),
 ('Hate Handicap',),
 ('Hocus Frida',),
 ('Kentuckian Giant',),
 ('Kill Brotherhood',),
 ('Muppet Mile',),
 ('Order Betrayed',),
 ('Pearl Destiny',),
 ('Perdition Fargo',),
 ('Psycho Shrunk',),
 ('Raiders Antitrust',),
 ('Rainbow Shock',),
 ('Roof Champion',),
 ('Sister Freddy',),
 ('Sky Miracle',),
 ('Suicides Silence',),
 ('Tadpole Park',),
 ('Treasure Command',),
 ('Villain Desperate',),
 ('Volume House',),
 ('Wake Jaws',),
 ('Walls Artist',)]

In [ ]:
#**24. Muestre el beneficio de cada una de las tiendas 1 y 2.**
#Para responder a esta pregunta, necesitamos saber la cantidad pagada y el Inventory_id para cada película alquilada al unirse (tablas de alquiler y pago) y el store_id para esa transacción de alquiler (unirse a la tabla de inventario).

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
select inventory.store_id, SUM(payment.amount)
FROM
payment
JOIN
rental
ON
payment.rental_id = rental.rental_id
JOIN
inventory
ON
inventory.inventory_id = rental.inventory_id
GROUP BY
store_id
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
result

[(1, Decimal('30628.91')), (2, Decimal('30683.13'))]

In [ ]:
#**25.  Muestra el beneficio de cada una de las tiendas 1 y 2 seguido del beneficio total de ambas tiendas**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
select inventory.store_id, SUM(payment.amount)
FROM
payment
JOIN
rental
ON
payment.rental_id = rental.rental_id
JOIN
inventory
ON
inventory.inventory_id = rental.inventory_id
GROUP BY
store_id
;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)

query = """
select SUM(payment.amount)
FROM
payment

;
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall()
print(result)

[(1, Decimal('30628.91')), (2, Decimal('30683.13'))]
[(Decimal('61312.04'),)]

In [ ]:
#**26. Cuente la cantidad de actores cuyos nombres no comienzan con una "A"**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 count(actor_id)
FROM
  actor
WHERE
  first_name LIKE 'A%';
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[(13,)]

In [ ]:
#**27. Busque el nombre del actor que comience con "P" seguido de (una *e* o una *a*) y luego cualquier otra letra**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT DISTINCT
  first_name
FROM
  actor
WHERE
  first_name LIKE 'Pe%' or first_name LIKE 'Pa%';
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Parker',), ('Penelope',)]

In [ ]:
#**28. Busque nombres de clientes que comiencen con "P" seguido de 5 letras**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 first_name
FROM
  actor
WHERE
  first_name LIKE 'P_____';
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Parker',)]

In [ ]:
#**29. Busque actores con PaRkEr como su nombre e ignore las letras mayúsculas y minúsculas. Luego seleccione actores llamados PaRkEr y haga coincidir el caso de la letra**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 first_name
FROM
  actor
WHERE
  first_name ~* 'PaRkEr';
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Parker',)]

In [ ]:
#**30. Busque nombres de actores que comiencen con "P" seguidos de cualquier letra de la a a la e y luego de cualquier otra letra**

In [ ]:
import psycopg2

# Connect to an existing database HEROKY _ nuestro nombre
conn = psycopg2.connect(
    host="ec2-54-73-58-75.eu-west-1.compute.amazonaws.com",
    database="d6jbvjn3b9tsce",
    user="mayknebhombpsq",
    password="dbc24635f5cbe1851f07d823eeada249c8751415ee900274b96110652bc94874",
    port=5432)

query = """
SELECT
 first_name
FROM
  actor
WHERE
  first_name SIMILAR TO 'P(a|b|c|c|e)%';
"""

#Creating a cursor object using the cursor() method
cursor = conn.cursor()
#Retrieving data
cursor.execute(query)
#Fetching 1st row from the table
#result = cursor.fetchone();
#print(result)
#Fetching 1st row from the table
result = cursor.fetchall();
result

[('Penelope',), ('Parker',), ('Penelope',), ('Penelope',), ('Penelope',)]